`timescale 1ns/1ps

module zx50_bus_arbiter_tb;

    // --- 1. System Clocks (Generated by Timebase) ---
    wire mclk;
    
    zx50_clock clk_gen (
        .mclk(mclk),
        .zclk() // Z80 clock not needed for isolated arbiter test
    );

    // --- 2. System Signals & State ---
    reg reset_n;
    reg [3:0] test_vector;
    reg [2:0] settle_counter;

    wire shadow_en_n  = test_vector[0];
    wire z80_card_hit = test_vector[1];
    wire z80_rd_n     = test_vector[2];
    wire shd_rw_n     = test_vector[3];

    wire z80_wait_n, shd_busy_n;
    wire z80_data_oe_n, shd_data_oe_n, d_dir;

    // --- 3. DUT Instantiation ---
    zx50_bus_arbiter dut (
        .mclk(mclk), .reset_n(reset_n),
        .shadow_en_n(shadow_en_n), .z80_card_hit(z80_card_hit),
        .z80_wait_n(z80_wait_n), .shd_busy_n(shd_busy_n),
        .z80_rd_n(z80_rd_n), .shd_rw_n(shd_rw_n),
        .z80_data_oe_n(z80_data_oe_n), .shd_data_oe_n(shd_data_oe_n), .d_dir(d_dir) 
    );

    // --- 4. Setup & Reset ---
    initial begin
        $dumpfile("waves/zx50_bus_arbiter.vcd");
        $dumpvars(0, zx50_bus_arbiter_tb);
        
        reset_n = 0;
        test_vector = 4'b0000;
        settle_counter = 3'b000;
        
        clk_gen.wait_mclk(5); // Hold reset for 5 clock cycles
        reset_n = 1;
    end

    // --- 5. State Generation ---
    always @(posedge mclk) begin
        if (reset_n) begin
            settle_counter <= settle_counter + 1'b1;
            
            // Allow 8 clock cycles for the state machine to transition and settle
            if (settle_counter == 3'b111) begin 
                if (test_vector == 4'b1111) begin
                    $display("=====================================================");
                    $display(" SUCCESS: All 16 Input States Tested.");
                    $display(" ZERO Bus Contention Violations Found.");
                    $display("=====================================================");
                    $finish;
                end else begin
                    test_vector <= test_vector + 1'b1;
                end
            end
        end
    end

    // --- 6. INVARIANT ASSERTIONS (Checked every clock cycle) ---
    always @(posedge mclk) begin
        if (reset_n) begin
            
            // INVARIANT 1: Mutual Exclusion on Data Bus
            if (z80_data_oe_n == 0 && shd_data_oe_n == 0) begin
                $display("FATAL [%0t]: Shared Data Bus Short Circuit Detected!", $time);
                $fatal(1); 
            end

            // INVARIANT 2: Z80 Protection (Wait state if closed)
            if (z80_card_hit && (z80_data_oe_n != 0) && (z80_wait_n != 0)) begin
                $display("FATAL [%0t]: Z80 hit the card but transceivers are closed without a WAIT state!", $time);
                $fatal(1);
            end

            // INVARIANT 3: Shadow Bus Protection (Busy state if closed)
            if (!shadow_en_n && (shd_data_oe_n != 0) && (shd_busy_n != 0)) begin
                $display("FATAL [%0t]: Shadow bus hit the card but transceivers are closed without S_BUSY!", $time);
                $fatal(1);
            end
        end
    end

    // --- System Watchdog Timer ---
    initial begin
        #150000; 
        $display("FATAL [%0t]: Watchdog Timer Expired!", $time);
        $fatal(1);
    end

endmodule