`timescale 1ns/1ps

module zx50_mmu_sram_tb;

    // --- 1. System Clocks (Generated by Timebase) ---
    wire mclk, zclk;
    
    zx50_clock clk_gen (
        .mclk(mclk),
        .zclk(zclk)
    );

    // --- 2. System Signals ---
    reg reset_n, boot_en_n;
    reg [3:0] id_sw;

    // --- 3. Z80 Backplane Buses (Driven by BFM) ---
    wire [15:0] z80_addr;
    wire [7:0]  z80_data;
    wire z80_mreq_n, z80_iorq_n, z80_rd_n, z80_wr_n, z80_m1_n;
    
    // --- 4. MMU / ATL Wires ---
    wire [3:0] atl_addr;
    wire [7:0] atl_data;
    wire atl_we_n, atl_oe_n, atl_ce_n;
    wire [7:0] p_hi;
    wire active, z80_card_hit, is_busy;

    // --- 5. BFM Instantiations ---

    // The Z80 Bus Master
    z80_cpu_util z80 (
        .clk(zclk), .addr(z80_addr), .data(z80_data),
        .mreq_n(z80_mreq_n), .iorq_n(z80_iorq_n), 
        .rd_n(z80_rd_n), .wr_n(z80_wr_n), .m1_n(z80_m1_n),
        .wait_n(1'b1) // No wait states needed for isolated MMU testing
    );

    // The Device Under Test
    zx50_mmu_sram dut (
        .mclk(mclk), .reset_n(reset_n), .boot_en_n(boot_en_n), .card_id_sw(id_sw),
        .z80_addr(z80_addr), .l_addr_hi(z80_addr[15:12]), .l_data(z80_data),
        .z80_iorq_n(z80_iorq_n), .z80_wr_n(z80_wr_n), .z80_mreq_n(z80_mreq_n),
        .atl_addr(atl_addr), .atl_data(atl_data), .atl_we_n(atl_we_n), .atl_oe_n(atl_oe_n),
        .p_addr_hi(p_hi), .active(active), .z80_card_hit(z80_card_hit), .is_busy(is_busy)
    );

    // The Structural LUT SRAM
    // Note: Since this is just the isolated MMU, we mock the top-level CE logic here
    assign atl_ce_n = !(z80_card_hit || is_busy);
    
    is61c256al lut_sram (
        .addr({11'b0, atl_addr}), // Pad the 4-bit MMU address to fit the 15-bit chip
        .data(atl_data),
        .ce_n(atl_ce_n), .oe_n(atl_oe_n), .we_n(atl_we_n)
    );

    // --- 6. Test Sequence ---
    reg [7:0] dummy_data;

    initial begin
        $dumpfile("waves/zx50_mmu_sram.vcd");
        $dumpvars(0, zx50_mmu_sram_tb);
        
        // Setup
        id_sw = 4'h0; boot_en_n = 0; // Boot override active
        
        // Boot Sequence
        reset_n = 1;      
        clk_gen.wait_mclk(5); 
        reset_n = 0;  
        clk_gen.wait_mclk(50); 
        reset_n = 1; 

        // Wait for the 16-cycle Hardware Wipe to finish
        clk_gen.wait_mclk(20); 

        // ==========================================
        // PHASE 1: Auto-Init 1:1 Mapping Check
        // ==========================================
        $display("[%0t] --- Testing Phase 1: Auto-Init 1:1 Mapping ---", $time);
        // Because boot_en_n = 0, page 8 (0x8000) should be claimed by this card
        
        fork
            // Thread A: Start the Z80 Read
            z80.mem_read(16'h8000, dummy_data); 
            
            // Thread B: Wait for T1 (MREQ drop) and check the translation
            begin
                wait(z80_mreq_n == 1'b0); 
                #15; // Give 15ns for LUT SRAM access time
                
                if (active === 1'b1 && p_hi === 8'h08 && z80_card_hit === 1'b1) begin
                    $display("****** PHASE 1 PASSED: Memory claimed, translated to Page 8 ******");
                end else begin
                    $display("!!!!!! PHASE 1 FAILED: active=%b, p_hi=%h, hit=%b !!!!!!", active, p_hi, z80_card_hit);
                    $fatal(1);
                end
            end
        join

        z80.wait_cycles(5); 

        // ==========================================
        // PHASE 2: Dynamic MMU Reprogramming Check
        // ==========================================
        $display("[%0t] --- Testing Phase 2: Z80 MMU I/O Write ---", $time);
        // OUT (0x30), 0xAA -> Writing physical page 0xAA to Bank 0x0
        z80.io_write(16'h0030, 8'hAA); 

        z80.wait_cycles(5); 

        // ==========================================
        // PHASE 3: Translation Verification
        // ==========================================
        $display("[%0t] --- Testing Phase 3: Translation Verification ---", $time);
        // Verify SRAM actually latched it by reading Bank 0x0
        
        fork
            z80.mem_read(16'h0000, dummy_data);
            begin
                wait(z80_mreq_n == 1'b0); 
                #15; // Give 15ns for LUT SRAM access time
                
                if (p_hi === 8'hAA) begin
                    $display("****** PHASE 3 PASSED: SRAM successfully updated to 0xAA ******");
                end else begin
                    $display("!!!!!! PHASE 3 FAILED: p_hi=%h (Expected 0xAA) !!!!!!", p_hi);
                    $fatal(1);
                end
            end
        join

        z80.wait_cycles(5); 
        $display("=====================================================");
        $display(" SUCCESS: All MMU Tests Passed.");
        $display("=====================================================");
        $finish;
    end

    // --- System Watchdog Timer ---
    initial begin
        #150000; 
        $display("FATAL [%0t]: Watchdog Timer Expired! Testbench deadlock detected.", $time);
        $fatal(1);
    end
endmodule