`timescale 1ns/1ps

module zx50_cpld_core_tb;

    // --- 1. System Clocks (Generated by the Timebase) ---
    wire mclk, zclk;
    
    zx50_clock clk_gen (
        .mclk(mclk),
        .zclk(zclk)
    );

    // --- 2. System Signals ---
    reg reset_n, boot_en_n;
    reg z80_iei;
    reg [3:0] card_id_sw;

    // --- 3. Z80 Backplane Buses (Driven by BFM) ---
    wire [15:0] z80_addr;
    wire [7:0]  z80_data;
    wire z80_mreq_n, z80_iorq_n, z80_rd_n, z80_wr_n, z80_m1_n;
    wire z80_wait_n, z80_ieo, z80_int_n;

    // --- 4. Shadow DMA Bus (Inactive for this test) ---
    wire shadow_en_n, shd_rw_n, shd_inc_n, shd_stb_n, shd_done_n, shd_busy_n;
    wire shd_c_dir, shd_c_oe_n;
    
    // Default Shadow Bus Pull-ups
    assign shadow_en_n = 1'b1; 
    assign shd_rw_n = 1'b1;

    // --- 5. CPLD Output Pins to Monitor ---
    wire [10:0] l_addr;
    wire [3:0]  atl_addr;
    wire [7:0]  atl_data;
    wire atl_we_n, atl_oe_n, atl_ce_n;
    wire ce0_n, ce1_n, ram_oe_n, ram_we_n;
    wire z80_data_oe_n, shd_data_oe_n, d_dir;

    // --- 6. The Duplex Handoff Logic ---
    wire [3:0] duplex_bus = (reset_n) ? {z80_iorq_n, z80_mreq_n, z80_wr_n, z80_rd_n} : card_id_sw;

    // --- 7. BFM Instantiations ---

    // Z80 Master
    z80_cpu_util z80 (
        .clk(zclk), .addr(z80_addr), .data(z80_data),
        .mreq_n(z80_mreq_n), .iorq_n(z80_iorq_n), 
        .rd_n(z80_rd_n), .wr_n(z80_wr_n), .m1_n(z80_m1_n),
        .wait_n(z80_wait_n) 
    );

    // The Device Under Test
    zx50_cpld_core dut (
        .mclk(mclk), .reset_n(reset_n), .boot_en_n(boot_en_n), 
        .duplex_in(duplex_bus), 
        .z80_m1_n(z80_m1_n), .z80_iei(z80_iei), .z80_ieo(z80_ieo),
        .z80_int_n(z80_int_n), .z80_wait_n(z80_wait_n),
        
        .z80_addr(z80_addr), .l_data(z80_data), 
        
        .shadow_en_n(shadow_en_n), .shd_rw_n(shd_rw_n), .shd_inc_n(shd_inc_n), 
        .shd_stb_n(shd_stb_n), .shd_done_n(shd_done_n), .shd_busy_n(shd_busy_n),
        .shd_c_dir(shd_c_dir), .shd_c_oe_n(shd_c_oe_n),
        
        .l_addr(l_addr), .atl_addr(atl_addr), .atl_data(atl_data),
        .atl_we_n(atl_we_n), .atl_oe_n(atl_oe_n), .atl_ce_n(atl_ce_n),
        .ce0_n(ce0_n), .ce1_n(ce1_n), .ram_oe_n(ram_oe_n), .ram_we_n(ram_we_n),
        .z80_data_oe_n(z80_data_oe_n), .shd_data_oe_n(shd_data_oe_n), .d_dir(d_dir)
    );

    // We MUST include the LUT here. If atl_data is floating, the CPLD 
    // won't know how to resolve atl_data[7], turning ce0_n/ce1_n into 'x'.
    // During an MMU write, route the Z80 data to the LUT model.
    assign atl_data = (!atl_we_n) ? z80_data : 8'hzz;
    
    is61c256al lut_sram (
        .addr({11'b0, atl_addr}), .data(atl_data),
        .ce_n(atl_ce_n), .oe_n(atl_oe_n), .we_n(atl_we_n)
    );

    // --- 8. Test Sequence ---
    reg [7:0] dummy_data;

    initial begin
        $dumpfile("waves/zx50_cpld_core.vcd");
        $dumpvars(0, zx50_cpld_core_tb);
        
        // Setup
        boot_en_n = 1; z80_iei = 1;
        card_id_sw = 4'hC; // Let's use Card ID 0xC (12)
        
        // Boot Sequence: Mimic an RC reset circuit
        reset_n = 1;      // Power on
        #50 reset_n = 0;  // RC circuit holds reset low
        #700 reset_n = 1; // RC circuit charges, releasing reset

        // Wait for the 16-cycle Hardware Wipe to finish (Using the new timebase!)
        clk_gen.wait_mclk(20); 

        // ==========================================
        // PHASE 1: Program MMU
        // ==========================================
        $display("[%0t] Phase 1: Programming MMU Page 0 to 0x45...", $time);
        // Base 0x30 | ID 0xC = Port 0x3C
        z80.io_write(16'h003C, 8'h45); 

        // Wait a few Z80 T-States before the next action
        z80.wait_cycles(5); 

        // ==========================================
        // PHASE 2: CPLD Output Validation (Write Cycle)
        // ==========================================
        $display("[%0t] Phase 2: Memory Write Validation...", $time);
        
        fork
            // Thread A: Fire the Z80 Write sequence
            z80.mem_write(16'h0123, 8'hAA);
            
            // Thread B: Wait for the exact moment WR drops
            begin
                wait(z80_wr_n == 1'b0); 
                #10; // Give the CPLD 10ns to propagate the signal
                
                // Verify transceivers are open and pointing inward
                if (z80_data_oe_n !== 1'b0 || d_dir !== 1'b1) begin
                    $display("FATAL: Transceiver write logic failed! oe_n=%b, dir=%b", z80_data_oe_n, d_dir);
                    $fatal(1);
                end
                
                // Verify the correct Chip Enable fired (0x45 -> bit 7 is 0, so ce0_n)
                if (ce0_n !== 1'b0 || ce1_n !== 1'b1 || ram_we_n !== 1'b0) begin
                    $display("FATAL: Main SRAM gating failed! ce0=%b, ce1=%b, we=%b", ce0_n, ce1_n, ram_we_n);
                    $fatal(1);
                end
                
                $display("--- Phase 2 Passed: CPLD routed write signals perfectly.");
            end
        join

        z80.wait_cycles(5); 

        // ==========================================
        // PHASE 3: CPLD Output Validation (Read Cycle)
        // ==========================================
        $display("[%0t] Phase 3: Memory Read Validation...", $time);
        
        fork
            // Thread A: Fire the Z80 Read sequence
            z80.mem_read(16'h0123, dummy_data);
            
            // Thread B: Wait for the exact moment RD drops
            begin
                wait(z80_rd_n == 1'b0); 
                #10; // Give the CPLD 10ns to propagate the signal
                
                // Verify transceivers are open and pointing outward
                if (z80_data_oe_n !== 1'b0 || d_dir !== 1'b0) begin
                    $display("FATAL: Transceiver read logic failed! oe_n=%b, dir=%b", z80_data_oe_n, d_dir);
                    $fatal(1);
                end
                
                // Verify Output Enable fired
                if (ce0_n !== 1'b0 || ram_oe_n !== 1'b0) begin
                    $display("FATAL: Main SRAM read gating failed! ce0=%b, oe=%b", ce0_n, ram_oe_n);
                    $fatal(1);
                end
                
                $display("--- Phase 3 Passed: CPLD routed read signals perfectly.");
            end
        join

        z80.wait_cycles(5);
        $display("=====================================================");
        $display(" SUCCESS: CPLD Core Logic is fully operational.");
        $display("=====================================================");
        $finish;
    end

    // --- System Watchdog Timer ---
    initial begin
        #150000; 
        $display("FATAL [%0t]: Watchdog Timer Expired!", $time);
        $fatal(1);
    end
endmodule