`timescale 1ns/1ps

module zx50_mem_card_tb;

    // --- 1. System Clocks (Generated by Timebase) ---
    wire mclk, zclk;
    
    zx50_clock clk_gen (
        .mclk(mclk),
        .zclk(zclk)
    );

    // --- 2. System Signals ---
    reg reset_n, boot_en_n;
    reg [3:0] card_id;
    reg z80_iei;
    
    // --- 3. Z80 Backplane Buses (Driven by BFM) ---
    wire [15:0] z80_addr;
    wire [7:0]  z80_data;
    wire z80_mreq_n, z80_iorq_n, z80_wr_n, z80_rd_n, z80_m1_n;
    wire z80_wait_n, z80_ieo, z80_int_n;

    // --- 4. Shadow Bus (Mock - Inactive) ---
    wire [15:0] shd_addr;
    wire [7:0]  shd_data;
    wire shd_en_n, shd_rw_n, shd_inc_n, shd_stb_n, shd_done_n, shd_busy_n;

    // Default Shadow Bus Pull-ups (keeps transceivers quiet)
    assign shd_en_n = 1'b1;
    assign shd_rw_n = 1'b1;

    // --- 5. BFM Instantiations ---

    // The Z80 Bus Master
    z80_cpu_util z80 (
        .clk(zclk),
        .addr(z80_addr),
        .data(z80_data),
        .mreq_n(z80_mreq_n),
        .iorq_n(z80_iorq_n),
        .rd_n(z80_rd_n),
        .wr_n(z80_wr_n),
        .m1_n(z80_m1_n),
        .wait_n(z80_wait_n)
    );

    // The Device Under Test (Full Digital Twin of the Card)
    zx50_mem_card dut (
        .mclk(mclk), .reset_n(reset_n), .boot_en_n(boot_en_n), .card_id_sw(card_id),
        .z80_addr(z80_addr), .z80_data(z80_data),
        .z80_mreq_n(z80_mreq_n), .z80_iorq_n(z80_iorq_n), .z80_wr_n(z80_wr_n), .z80_rd_n(z80_rd_n),
        .z80_m1_n(z80_m1_n), .z80_iei(z80_iei),
        .z80_wait_n(z80_wait_n), .z80_ieo(z80_ieo), .z80_int_n(z80_int_n),
        .shd_addr(shd_addr), .shd_data(shd_data),
        .shd_en_n(shd_en_n), .shd_rw_n(shd_rw_n), .shd_inc_n(shd_inc_n), 
        .shd_stb_n(shd_stb_n), .shd_done_n(shd_done_n), .shd_busy_n(shd_busy_n)
    );

    // --- 6. Test Sequence ---
    reg [7:0] read_val; 

    initial begin
        $dumpfile("waves/zx50_mem_card.vcd");
        $dumpvars(0, zx50_mem_card_tb);
        
        // Initial setup
        boot_en_n = 1; card_id = 4'h0; z80_iei = 1;
        
        // Boot Sequence
        reset_n = 1;      
        clk_gen.wait_mclk(5); // Wait a few clock cycles
        reset_n = 0;  
        clk_gen.wait_mclk(50); // Hold reset active for a while
        reset_n = 1; 

        // Wait for the 16-cycle MMU Hardware Wipe to finish
        clk_gen.wait_mclk(20); 

        // ==========================================
        // STEP 1: Program MMU
        // ==========================================
        $display("[%0t] Step 1: Programming MMU Page 0...", $time);
        // I/O Port 0x30 = Bank 0x0, Data = Physical Page 0x85
        z80.io_write(16'h0030, 8'h85); 

        // Wait a few Z80 T-States before the next command
        z80.wait_cycles(5);

        // ==========================================
        // STEP 2: Write to SRAM
        // ==========================================
        $display("[%0t] Step 2: Writing to SRAM...", $time);
        // Target Bank 0x0, Offset 0x0123. (Will map to physical 0x85123)
        z80.mem_write(16'h0123, 8'hA5);

        z80.wait_cycles(5);

        // ==========================================
        // STEP 3: Read back from SRAM
        // ==========================================
        $display("[%0t] Step 3: Reading back from SRAM...", $time);
        z80.mem_read(16'h0123, read_val);
        
        // Validation Check
        if (read_val === 8'hA5) begin
            $display("SUCCESS: Data Match! MMU and SRAM working perfectly.");
        end 
        else begin
            $display("!!! FAILURE: Expected A5, got %h !!!", read_val);
            $fatal(1);
        end

        z80.wait_cycles(5);
        $finish;
    end

    // --- System Watchdog Timer ---
    initial begin
        #150000; 
        $display("FATAL [%0t]: Watchdog Timer Expired! Testbench deadlock detected.", $time);
        $fatal(1);
    end

endmodule