/***************************************************************************************
 * FILE: src/fpu_rom_map.vh
 * DESCRIPTION: Auto-generated Flash ROM Address Map for ZX50 FPU Coprocessor.
 * DO NOT EDIT MANUALLY - Generated by tools/build_flash.py
 ***************************************************************************************/

`ifndef FPU_ROM_MAP_VH
`define FPU_ROM_MAP_VH

  `define FLASH_RECIP_BASE         15'h0400
  `define FLASH_SQRT_BASE          15'h0600
  `define FLASH_EXP2_BASE          15'h0800
  `define FLASH_LOG2_BASE          15'h0A00
  `define FLASH_SIN_BASE           15'h0C00
  `define FLASH_COS_BASE           15'h0E00
  `define FLASH_TAN_BASE           15'h1000
  `define FLASH_LN_BASE            15'h1200
  `define FLASH_LOG10_BASE         15'h1400
  `define FLASH_CONST_BASE         15'h1600
  `define FLASH_CORDIC_ATAN32_BASE 15'h1800
  `define FLASH_CORDIC_ATAN64_BASE 15'h1900
  `define FLASH_TRIG_CONST_BASE    15'h1B00
  `define FLASH_CHEB_BASE          15'h1C00

  // FPU Constants Word Slot Map (32-bit words from FLASH_CONST_BASE)
  `define CONST_SLOT_PI_F32             6'd0
  `define CONST_SLOT_PI_F64             6'd2
  `define CONST_SLOT_E_F32              6'd4
  `define CONST_SLOT_E_F64              6'd6
  `define CONST_SLOT_LN2_F32            6'd8
  `define CONST_SLOT_LN2_F64            6'd10
  `define CONST_SLOT_LOG2E_F32          6'd12
  `define CONST_SLOT_LOG2E_F64          6'd14
  `define CONST_SLOT_LOG2_10_F32        6'd16
  `define CONST_SLOT_LOG2_10_F64        6'd18
  `define CONST_SLOT_LOG10_2_F32        6'd20
  `define CONST_SLOT_LOG10_2_F64        6'd22
  `define CONST_SLOT_SQRT2_F32          6'd24
  `define CONST_SLOT_SQRT2_F64          6'd26
  `define CONST_SLOT_INV_SQRT2_F32      6'd28
  `define CONST_SLOT_INV_SQRT2_F64      6'd30
  `define CONST_SLOT_ONE_F32            6'd32
  `define CONST_SLOT_ONE_F64            6'd33
  `define CONST_SLOT_NAN_F32            6'd35
  `define CONST_SLOT_NAN_F64            6'd36
  `define CONST_SLOT_POS_INF_F32        6'd38
  `define CONST_SLOT_NEG_INF_F32        6'd39
  `define CONST_SLOT_POS_INF_F64        6'd40
  `define CONST_SLOT_NEG_INF_F64        6'd42
  `define CONST_SLOT_TWO_OVER_PI_F32    6'd44
  `define CONST_SLOT_TWO_OVER_PI_F64    6'd45
  `define CONST_SLOT_CW_C1_F32          6'd47
  `define CONST_SLOT_CW_C2_F32          6'd48
  `define CONST_SLOT_CW_C1_F64          6'd49
  `define CONST_SLOT_CW_C2_F64          6'd51
  `define CONST_SLOT_CW_C3_F64          6'd53
  `define CONST_SLOT_CORDIC_INV_K_32    6'd55
  `define CONST_SLOT_CORDIC_INV_K_64    6'd56
  `define CONST_SLOT_LN10_F32           6'd58
  `define CONST_SLOT_LN10_F64           6'd60

  // Chebyshev & Polynomial Coefficients Word Slot Map (32-bit words from FLASH_CHEB_BASE)
  `define CHEB_SLOT_EXP2_C1            6'd1
  `define CHEB_SLOT_EXP2_C2            6'd2
  `define CHEB_SLOT_EXP2_C3            6'd3
  `define CHEB_SLOT_EXP2_C4            6'd4
  `define CHEB_SLOT_EXP2_C5            6'd5
  `define CHEB_SLOT_EXP2_C6            6'd6
  `define CHEB_SLOT_LOG2_C0            6'd7
  `define CHEB_SLOT_LOG2_C1            6'd8
  `define CHEB_SLOT_LOG2_C2            6'd9
  `define CHEB_SLOT_LOG2_C3            6'd10
  `define CHEB_SLOT_SQRT2_MANT         6'd11

`endif // FPU_ROM_MAP_VH
