[pytest]
cache_dir = /tmp/.pytest_cache
testpaths = fpu_emu/tests fpu_asm/tests
norecursedirs = fpu_emu_v1
addopts = --ignore=fpu_emu_v1 --cov=fpu_emu --cov-report=term-missing

[coverage:run]
data_file = /tmp/.coverage
