#!/usr/bin/env python3
"""
tools/build_flash.py
ZX50 FPU Flash ROM LUT Generator & Serializer

Defines individual generator functions for each lookup table (Quarter-Square,
Reciprocal, Sqrt Seed, Exp2, Log2) and serializes them into:
  1. bin/fpu_flash.bin  - Raw 32KB binary image for EEPROM/Flash programmers
  2. sim/fpu_rom.hex    - Verilog $readmemh image for simulation
  3. src/fpu_rom_map.vh - Verilog header containing memory base addresses
"""

import math
import os

# ROM Parameters
FLASH_SIZE        = 32768  # 32 KB active region for CA[14:0]
FLASH_QS_BASE     = 0x0000  # Quarter-Square Table (1022 bytes)
FLASH_RECIP_BASE  = 0x0400  # Reciprocal Table (512 bytes)
FLASH_SQRT_BASE   = 0x0600  # Square Root Seed Table (512 bytes)
FLASH_EXP2_BASE   = 0x0800  # Exp2 Table (512 bytes)
FLASH_LOG2_BASE   = 0x0A00  # Log2 Table (512 bytes)

HEADER_FILE = "src/fpu_rom_map.vh"
HEX_FILE    = "sim/fpu_rom.hex"
BIN_FILE    = "bin/fpu_flash.bin"


# =============================================================================
# Individual Lookup Table Generators
# =============================================================================
def generate_qs_table() -> bytearray:
    """Table 1: Quarter-Square [ f(n) = floor(n^2 / 4) ] for n in [0..510]"""
    data = bytearray(511 * 2)
    for n in range(511):
        val = (n * n) // 4
        data[n * 2]     = val & 0xFF
        data[n * 2 + 1] = (val >> 8) & 0xFF
    return data


def generate_recip_table() -> bytearray:
    """Table 2: Reciprocal [ f(x) = ceil(65536 / x) ] for x in [1..255]"""
    data = bytearray(256 * 2)
    for x in range(1, 256):
        val = min(65535, math.ceil(65536.0 / x))
        data[x * 2]     = val & 0xFF
        data[x * 2 + 1] = (val >> 8) & 0xFF
    return data


def generate_sqrt_table() -> bytearray:
    """Table 3: Square Root Seeds [ f(x) = sqrt(x) * 256 ] for x in [0..255]"""
    data = bytearray(256 * 2)
    for x in range(256):
        val = int(math.sqrt(x) * 256) & 0xFFFF
        data[x * 2]     = val & 0xFF
        data[x * 2 + 1] = (val >> 8) & 0xFF
    return data


def generate_exp2_table() -> bytearray:
    """Table 4: Exp2 [ f(x) = 2^(x/256) * 256 ] for x in [0..255]"""
    data = bytearray(256 * 2)
    for x in range(256):
        val = int(2 ** (x / 256.0) * 256) & 0xFFFF
        data[x * 2]     = val & 0xFF
        data[x * 2 + 1] = (val >> 8) & 0xFF
    return data


def generate_log2_table() -> bytearray:
    """Table 5: Log2 [ f(x) = log2(1 + x/256) * 256 ] for x in [0..255]"""
    data = bytearray(256 * 2)
    for x in range(256):
        val = int(math.log2(1.0 + (x / 256.0)) * 256) & 0xFFFF
        data[x * 2]     = val & 0xFF
        data[x * 2 + 1] = (val >> 8) & 0xFF
    return data


# =============================================================================
# In-Memory Flash Population Helper (Used by fpu_sim.py)
# =============================================================================
def populate_flash_memory(flash_mem: bytearray) -> bytearray:
    """Populate an existing 32KB bytearray with all Flash LUTs at their base addresses."""
    qs = generate_qs_table()
    recip = generate_recip_table()
    sqrt = generate_sqrt_table()
    exp2 = generate_exp2_table()
    log2 = generate_log2_table()

    flash_mem[FLASH_QS_BASE : FLASH_QS_BASE + len(qs)] = qs
    flash_mem[FLASH_RECIP_BASE : FLASH_RECIP_BASE + len(recip)] = recip
    flash_mem[FLASH_SQRT_BASE : FLASH_SQRT_BASE + len(sqrt)] = sqrt
    flash_mem[FLASH_EXP2_BASE : FLASH_EXP2_BASE + len(exp2)] = exp2
    flash_mem[FLASH_LOG2_BASE : FLASH_LOG2_BASE + len(log2)] = log2

    return flash_mem


def generate_flash_image() -> bytearray:
    """Generate a 32KB Flash ROM binary image pre-filled with 0xFF."""
    image = bytearray([0xFF] * FLASH_SIZE)
    return populate_flash_memory(image)


# =============================================================================
# Verilog Header & Hex Serialization
# =============================================================================
def write_verilog_header(header_path: str):
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, "w") as f:
        f.write("/***************************************************************************************\n")
        f.write(" * FILE: src/fpu_rom_map.vh\n")
        f.write(" * DESCRIPTION: Auto-generated Flash ROM Address Map for ZX50 FPU Coprocessor.\n")
        f.write(" * DO NOT EDIT MANUALLY - Generated by tools/build_flash.py\n")
        f.write(" ***************************************************************************************/\n\n")
        f.write("`ifndef FPU_ROM_MAP_VH\n`define FPU_ROM_MAP_VH\n\n")
        f.write(f"  `define FLASH_QS_BASE     15'h{FLASH_QS_BASE:04X}\n")
        f.write(f"  `define FLASH_RECIP_BASE  15'h{FLASH_RECIP_BASE:04X}\n")
        f.write(f"  `define FLASH_SQRT_BASE   15'h{FLASH_SQRT_BASE:04X}\n")
        f.write(f"  `define FLASH_EXP2_BASE   15'h{FLASH_EXP2_BASE:04X}\n")
        f.write(f"  `define FLASH_LOG2_BASE   15'h{FLASH_LOG2_BASE:04X}\n\n")
        f.write("`endif // FPU_ROM_MAP_VH\n")


def write_verilog_hex(hex_path: str, flash_image: bytearray):
    os.makedirs(os.path.dirname(hex_path), exist_ok=True)
    with open(hex_path, "w") as f:
        for byte in flash_image:
            f.write(f"{byte:02X}\n")


def main():
    os.makedirs("bin", exist_ok=True)
    os.makedirs("sim", exist_ok=True)

    image = generate_flash_image()

    with open(BIN_FILE, "wb") as f:
        f.write(image)

    write_verilog_hex(HEX_FILE, image)
    write_verilog_header(HEADER_FILE)

    print(f"[*] Generated Binary Image: {BIN_FILE} ({len(image)} bytes)")
    print(f"[*] Generated Simulation Hex: {HEX_FILE}")
    print(f"[*] Generated Verilog Header: {HEADER_FILE}")


if __name__ == "__main__":
    main()