#!/usr/bin/env python3
"""
tools/fpu_sim_microcode.py
ZX50 FPU Microcode ROM & Sequence Program Definitions
Defines cycle-by-cycle micro-instructions for CPLD execution.
NO MATH OPERATORS ALLOWED IN THIS FILE.
"""

from fpu_sim_alu import (
    ALU_PASS_X,
    ALU_ADD,
    ALU_SUB,
    ALU_ABS_DIFF,
    ALU_SWAP_BYTES,
    ALU_PASS_ZERO,
    MUX_ACC,
    MUX_OPB,
    MUX_TMP0,
    MUX_TMP1,
    MEM_NOP,
    MEM_RD_TOS,
    MEM_RD_NOS,
    MEM_RD_FLASH_QS,
    MEM_RD_FLASH_REC,
    MEM_RD_FLASH_SQRT,
    MEM_RD_FLASH_EXP2,
    MEM_RD_FLASH_LOG2,
    MEM_RD_FLASH_SIN,
    MEM_RD_FLASH_COS,
    MEM_RD_FLASH_TAN,
    MEM_RD_FLASH_LN,
    MEM_RD_FLASH_LOG10,
    MEM_WR_NOS,
    LD_NONE,
    LD_ACC,
    LD_OPB,
    LD_TMP0,
    LD_TMP1,
    LD_TMP0_LO,
    LD_TMP0_HI,
    LD_TMP1_LO,
    LD_TMP1_HI,
    SEQ_NEXT,
    SEQ_LOOP,
    SEQ_DONE, MEM_WR_TOS,
)

ENTRY_POINTS = {
    'ADD':       0x00,
    'SUB':       0x05,
    'MUL':       0x0A,
    'DIV':       0x19,
    'SQRT_INT':  0x2D,
    'SQRT_FX':   0x34,
    'LOG2':      0x3B,
    'EXP':       0x42,
    'POW':       0x49,
    'SIN':       0x5C,
    'COS':       0x62,
    'TAN':       0x68,
    'LN':        0x6E,
    'LOG10':     0x74,
    'CHS':       0x7F,
}

UROM = {
    # --- OP_ADD (0x00 - 0x04) --- 4-byte serial addition loop
    0x00: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x01: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_OPB, SEQ_NEXT),
    0x02: (ALU_ADD, MUX_OPB, MUX_ACC, MEM_WR_NOS, LD_NONE, SEQ_NEXT),
    0x03: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_LOOP),
    0x04: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_DONE),

    # --- OP_SUB (0x05 - 0x09) --- 4-byte serial subtraction loop
    0x05: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x06: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_OPB, SEQ_NEXT),
    0x07: (ALU_SUB, MUX_OPB, MUX_ACC, MEM_WR_NOS, LD_NONE, SEQ_NEXT),
    0x08: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_LOOP),
    0x09: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_DONE),

    # --- OP_MUL (0x0A - 0x18) --- Quarter-Square 8x8 -> 16 product pipeline
    0x0A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),         # ACC <= SRAM[TOS + byte_cnt]
    0x0B: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_OPB, SEQ_NEXT),         # OPB <= SRAM[NOS + byte_cnt]
    0x0C: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),             # TMP0 <= ACC + OPB (9-bit sum)
    0x0D: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1, SEQ_NEXT),        # TMP1 <= |ACC - OPB|
    0x0E: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),     # ACC <= Flash_QS[TMP0]_LO
    0x0F: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT), # TMP0_HI <= Flash_QS[TMP0]_HI
    0x10: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0_LO, SEQ_NEXT),        # TMP0_LO <= ACC
    0x11: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),     # OPB <= Flash_QS[TMP1]_LO
    0x12: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT), # TMP1_HI <= Flash_QS[TMP1]_HI
    0x13: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),        # TMP1_LO <= OPB
    0x14: (ALU_SUB, MUX_TMP0, MUX_TMP1, MEM_NOP, LD_TMP0, SEQ_NEXT),           # TMP0 <= QS(a+b) - QS(|a-b|)
    0x15: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),      # Write product LO -> NOS[0]
    0x16: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),  # Write product HI -> NOS[1]
    0x17: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[2]
    0x18: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_DIV (0x19 - 0x2C) --- Reciprocal Multiplication via Flash
    0x19: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_OPB, SEQ_NEXT),         # OPB <= TOS[0] (Divisor)
    0x1A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_ACC, SEQ_NEXT),         # ACC <= NOS[0] (Dividend)
    0x1B: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_RD_FLASH_REC, LD_TMP0_LO, SEQ_NEXT), # TMP0_LO <= Recip[OPB]_LO
    0x1C: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_RD_FLASH_REC, LD_TMP0_HI, SEQ_NEXT), # TMP0_HI <= Recip[OPB]_HI
    0x1D: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1, SEQ_NEXT),           # TMP1 <= ACC
    0x1E: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_NOP, LD_OPB, SEQ_NEXT),        # OPB <= TMP0_HI (swap bytes to load HI)
    0x1F: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),             # Partial product via QS
    0x20: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1, SEQ_NEXT),
    0x21: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),
    0x22: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT),
    0x23: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0_LO, SEQ_NEXT),
    0x24: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),
    0x25: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT),
    0x26: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),
    0x27: (ALU_SUB, MUX_TMP0, MUX_TMP1, MEM_NOP, LD_TMP0, SEQ_NEXT),           # Quotient
    0x28: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),
    0x29: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),      # Write Quotient LO -> NOS[0]
    0x2A: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[1]
    0x2B: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[2]
    0x2C: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_SQRT_INT (0x2D - 0x33) --- Integer Square Root
    0x2D: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x2E: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SQRT, LD_TMP0_LO, SEQ_NEXT),
    0x2F: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SQRT, LD_TMP0_HI, SEQ_NEXT),
    0x30: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),       # TMP0_LO <= seed_hi
    0x31: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write integer sqrt -> NOS[0]
    0x32: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[1]
    0x33: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Pad upper bytes

    # --- OP_SQRT_FX (0x34 - 0x3A) --- Fixed-Point 16.16 Square Root
    0x34: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x35: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SQRT, LD_TMP0_LO, SEQ_NEXT),
    0x36: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SQRT, LD_TMP0_HI, SEQ_NEXT),
    0x37: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x38: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x39: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x3A: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_LOG2 (0x3B - 0x41) ---
    0x3B: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x3C: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG2, LD_TMP0_LO, SEQ_NEXT),
    0x3D: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG2, LD_TMP0_HI, SEQ_NEXT),
    0x3E: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x3F: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x40: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x41: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_EXP (0x42 - 0x48) ---
    0x42: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x43: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_EXP2, LD_TMP0_LO, SEQ_NEXT),
    0x44: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_EXP2, LD_TMP0_HI, SEQ_NEXT),
    0x45: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x46: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x47: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x48: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_POW (0x49 - 0x5B) ---
    0x49: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x4A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG2, LD_TMP0_LO, SEQ_NEXT),
    0x4B: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG2, LD_TMP0_HI, SEQ_NEXT),
    0x4C: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_OPB, SEQ_NEXT),
    0x4D: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_NOP, LD_ACC, SEQ_NEXT),
    0x4E: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1, SEQ_NEXT),
    0x4F: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),
    0x50: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),
    0x51: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT),
    0x52: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),
    0x53: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT),
    0x54: (ALU_SUB, MUX_TMP1, MUX_TMP0, MEM_NOP, LD_TMP1, SEQ_NEXT),
    0x55: (ALU_SWAP_BYTES, MUX_TMP1, MUX_OPB, MEM_NOP, LD_ACC, SEQ_NEXT),
    0x56: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_EXP2, LD_TMP0_LO, SEQ_NEXT),
    0x57: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_EXP2, LD_TMP0_HI, SEQ_NEXT),
    0x58: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x59: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x5A: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x5B: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_SIN (0x5C - 0x62) ---
    0x5C: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x5D: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SIN, LD_TMP0_LO, SEQ_NEXT),
    0x5E: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SIN, LD_TMP0_HI, SEQ_NEXT),
    0x5F: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x60: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x61: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x62: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_COS (0x63 - 0x69) ---
    0x63: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x64: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_COS, LD_TMP0_LO, SEQ_NEXT),
    0x65: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_COS, LD_TMP0_HI, SEQ_NEXT),
    0x66: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x67: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x68: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x69: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_TAN (0x6A - 0x70) ---
    0x6A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x6B: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_TAN, LD_TMP0_LO, SEQ_NEXT),
    0x6C: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_TAN, LD_TMP0_HI, SEQ_NEXT),
    0x6D: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x6E: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x6F: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x70: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_LN (0x71 - 0x77) ---
    0x71: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x72: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LN, LD_TMP0_LO, SEQ_NEXT),
    0x73: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LN, LD_TMP0_HI, SEQ_NEXT),
    0x74: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x75: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x76: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x77: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_LOG10 (0x78 - 0x7E) ---
    0x78: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x79: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG10, LD_TMP0_LO, SEQ_NEXT),
    0x7A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG10, LD_TMP0_HI, SEQ_NEXT),
    0x7B: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x7C: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x7D: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x7E: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_CHS (0x7F - 0x83) --- Two's Complement Negation Loop
    0x7F: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_NOP, LD_ACC, SEQ_NEXT),          # ACC <= 0
    0x80: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_OPB, SEQ_NEXT),         # OPB <= SRAM[TOS + byte_cnt]
    0x81: (ALU_SUB, MUX_ACC, MUX_OPB, MEM_WR_TOS, LD_NONE, SEQ_NEXT),            # SRAM[NOS] <= ACC (0) - OPB - carry
    0x82: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_LOOP),           # Loop on BYTE_CNT
    0x83: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_DONE),
}
