#!/usr/bin/env python3
"""
tools/fpu_sim_microcode.py
ZX50 FPU Microcode ROM & Sequence Program Definitions
Defines cycle-by-cycle micro-instructions for CPLD execution.
NO MATH OPERATORS ALLOWED IN THIS FILE.
"""

from fpu_sim_alu import (
    ALU_PASS_X,
    ALU_ADD,
    ALU_SUB,
    ALU_ABS_DIFF,
    ALU_SWAP_BYTES,
    ALU_PASS_ZERO,
    MUX_ACC,
    MUX_OPB,
    MUX_TMP0,
    MUX_TMP1,
    MEM_NOP,
    MEM_RD_TOS,
    MEM_RD_NOS,
    MEM_RD_FLASH_QS,
    MEM_RD_FLASH_REC,
    MEM_RD_FLASH_SQRT,
    MEM_RD_FLASH_EXP2,
    MEM_RD_FLASH_LOG2,
    MEM_RD_FLASH_SIN,
    MEM_RD_FLASH_COS,
    MEM_RD_FLASH_TAN,
    MEM_RD_FLASH_LN,
    MEM_RD_FLASH_LOG10,
    MEM_WR_NOS,
    MEM_WR_TOS,
    MEM_RD_SCRATCH,
    MEM_WR_SCRATCH,
    LD_NONE,
    LD_ACC,
    LD_OPB,
    LD_TMP0,
    LD_TMP1,
    LD_TMP0_LO,
    LD_TMP0_HI,
    LD_TMP1_LO,
    LD_TMP1_HI,
    SEQ_NEXT,
    SEQ_LOOP,
    SEQ_DONE,
)

ENTRY_POINTS = {
    'ADD':       0x00,
    'SUB':       0x05,
    'MUL':       0x0A,
    'MUL_INT':   0x0A,
    'MUL_FX':    0x0A,
    'DIV':       0x60,
    'SQRT_INT':  0x80,
    'SQRT_FX':   0x88,
    'LOG2':      0x90,
    'EXP':       0xA0,
    'POW':       0xB0,
    'SIN':       0xC8,
    'COS':       0xD0,
    'TAN':       0xD8,
    'LN':        0xE0,
    'LOG10':     0xE8,
    'CHS':       0xF0,
}

UROM = {
    # --- OP_ADD (0x00 - 0x04) --- 4-byte serial addition loop
    0x00: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x01: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_OPB, SEQ_NEXT),
    0x02: (ALU_ADD, MUX_OPB, MUX_ACC, MEM_WR_NOS, LD_NONE, SEQ_NEXT),
    0x03: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_LOOP),
    0x04: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_DONE),

    # --- OP_SUB (0x05 - 0x09) --- 4-byte serial subtraction loop
    0x05: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x06: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_OPB, SEQ_NEXT),
    0x07: (ALU_SUB, MUX_OPB, MUX_ACC, MEM_WR_NOS, LD_NONE, SEQ_NEXT),
    0x08: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_LOOP),
    0x09: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_DONE),

    # --- OP_MUL (0x0A - 0x5A) --- Full 16x16 -> 32-Bit QS Cross-Multiply
    # Stash Stage: Load NOS[0..1] & TOS[0..1] into registers, write sequentially to SCRATCH[0..3]
    0x0A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_TMP0_LO, SEQ_NEXT),     # TMP0_LO <= NOS[0] (a0)
    0x0B: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_TMP0_HI, SEQ_NEXT),     # TMP0_HI <= NOS[1] (a1)
    0x0C: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_TMP1_LO, SEQ_NEXT),     # TMP1_LO <= TOS[0] (b0)
    0x0D: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_TMP1_HI, SEQ_NEXT),     # TMP1_HI <= TOS[1] (b1)
    0x0E: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_SCRATCH, LD_NONE, SEQ_NEXT),   # SCRATCH[0] <= a0
    0x0F: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_SCRATCH, LD_NONE, SEQ_NEXT),# SCRATCH[1] <= a1
    0x10: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_WR_SCRATCH, LD_NONE, SEQ_NEXT),   # SCRATCH[2] <= b0
    0x11: (ALU_SWAP_BYTES, MUX_TMP1, MUX_OPB, MEM_WR_SCRATCH, LD_NONE, SEQ_NEXT),# SCRATCH[3] <= b1

    # Pass 1: P00 = a0 * b0
    0x12: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_ACC, SEQ_NEXT),     # ACC <= SCRATCH[0] (a0)
    0x13: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_NONE, SEQ_NEXT),    # Dummy SCRATCH[1]
    0x14: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_OPB, SEQ_NEXT),     # OPB <= SCRATCH[2] (b0)
    0x15: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),             # TMP0 <= a0 + b0
    0x16: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1_HI, SEQ_NEXT),    # TMP1_HI <= 0
    0x17: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),     # TMP1_LO <= |a0 - b0|
    0x18: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),  # ACC <= QS(a0+b0)_LO
    0x19: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT),# TMP0_HI <= QS(a0+b0)_HI
    0x1A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0_LO, SEQ_NEXT),       # TMP0 <= QS(a0+b0)
    0x1B: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),  # OPB <= QS(|a0-b0|)_LO
    0x1C: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT),# TMP1_HI <= QS(|a0-b0|)_HI
    0x1D: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),       # TMP1 <= QS(|a0-b0|)
    0x1E: (ALU_SUB, MUX_TMP0, MUX_TMP1, MEM_NOP, LD_TMP0, SEQ_NEXT),           # TMP0 <= P00 (a0 * b0)
    0x1F: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),       # NOS[0] <= P00_LO (r0)
    0x20: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),   # NOS[1] <= P00_HI (c0)

    # Pass 2: P01 = a0 * b1
    0x21: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_ACC, SEQ_NEXT),     # ACC <= SCRATCH[0] (a0)
    0x22: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_NONE, SEQ_NEXT),    # Dummy SCRATCH[1]
    0x23: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_NONE, SEQ_NEXT),    # Dummy SCRATCH[2]
    0x24: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_OPB, SEQ_NEXT),     # OPB <= SCRATCH[3] (b1)
    0x25: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),             # TMP0 <= a0 + b1
    0x26: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1_HI, SEQ_NEXT),    # TMP1_HI <= 0
    0x27: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),     # TMP1_LO <= |a0 - b1|
    0x28: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),  # ACC <= QS(a0+b1)_LO
    0x29: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT),# TMP0_HI <= QS(a0+b1)_HI
    0x2A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0_LO, SEQ_NEXT),       # TMP0 <= QS(a0+b1)
    0x2B: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),  # OPB <= QS(|a0-b1|)_LO
    0x2C: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT),# TMP1_HI <= QS(|a0-b1|)_HI
    0x2D: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),       # TMP1 <= QS(|a0-b1|)
    0x2E: (ALU_SUB, MUX_TMP0, MUX_TMP1, MEM_NOP, LD_TMP0, SEQ_NEXT),           # TMP0 <= P01 (a0 * b1)
    0x2F: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_NONE, SEQ_NEXT),        # Dummy NOS[0]
    0x30: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_ACC, SEQ_NEXT),         # ACC <= NOS[1] (c0)
    0x31: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_NOP, LD_OPB, SEQ_NEXT),           # OPB <= P01_LO
    0x32: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_OPB, SEQ_NEXT),              # OPB <= c0 + P01_LO
    0x33: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_ACC, SEQ_NEXT),         # ACC <= NOS[0] (r0)
    0x34: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),       # NOS[0] <= r0
    0x35: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),       # NOS[1] <= c0 + P01_LO

    # Pass 3: P10 = a1 * b0
    0x36: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_NONE, SEQ_NEXT),    # Dummy SCRATCH[0]
    0x37: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_ACC, SEQ_NEXT),     # ACC <= SCRATCH[1] (a1)
    0x38: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_OPB, SEQ_NEXT),     # OPB <= SCRATCH[2] (b0)
    0x39: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),             # TMP0 <= a1 + b0
    0x3A: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1_HI, SEQ_NEXT),    # TMP1_HI <= 0
    0x3B: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),     # TMP1_LO <= |a1 - b0|
    0x3C: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),  # ACC <= QS(a1+b0)_LO
    0x3D: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT),# TMP0_HI <= QS(a1+b0)_HI
    0x3E: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0_LO, SEQ_NEXT),       # TMP0 <= QS(a1+b0)
    0x3F: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),  # OPB <= QS(|a1-b0|)_LO
    0x40: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT),# TMP1_HI <= QS(|a1-b0|)_HI
    0x41: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),       # TMP1 <= QS(|a1-b0|)
    0x42: (ALU_SUB, MUX_TMP0, MUX_TMP1, MEM_NOP, LD_TMP0, SEQ_NEXT),           # TMP0 <= P10 (a1 * b0)
    0x43: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_ACC, SEQ_NEXT),         # ACC <= NOS[0] (r0)
    0x44: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_TMP1_LO, SEQ_NEXT),     # TMP1_LO <= NOS[1] (r1)
    0x45: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_NOP, LD_OPB, SEQ_NEXT),           # OPB <= P10_LO
    0x46: (ALU_ADD, MUX_TMP1, MUX_OPB, MEM_NOP, LD_OPB, SEQ_NEXT),              # OPB <= final r1

    # Pass 4: P11 = a1 * b1
    0x47: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_NONE, SEQ_NEXT),    # Dummy SCRATCH[0]
    0x48: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_ACC, SEQ_NEXT),     # ACC <= SCRATCH[1] (a1)
    0x49: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_NONE, SEQ_NEXT),    # Dummy SCRATCH[2]
    0x4A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_SCRATCH, LD_TMP1_LO, SEQ_NEXT), # TMP1_LO <= SCRATCH[3] (b1)
    0x4B: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_NOP, LD_OPB, SEQ_NEXT),           # OPB <= b1
    0x4C: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),             # TMP0 <= a1 + b1
    0x4D: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1_HI, SEQ_NEXT),    # TMP1_HI <= 0
    0x4E: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),     # TMP1_LO <= |a1 - b1|
    0x4F: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),  # ACC <= QS(a1+b1)_LO
    0x50: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT),# TMP0_HI <= QS(a1+b1)_HI
    0x51: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0_LO, SEQ_NEXT),       # TMP0 <= QS(a1+b1)
    0x52: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),  # OPB <= QS(|a1-b1|)_LO
    0x53: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT),# TMP1_HI <= QS(|a1-b1|)_HI
    0x54: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),       # TMP1 <= QS(|a1-b1|)
    0x55: (ALU_SUB, MUX_TMP0, MUX_TMP1, MEM_NOP, LD_TMP0, SEQ_NEXT),           # TMP0 <= P11 (a1 * b1)

    # Write Final Result [r0, r1, P11_LO, P11_HI] to NOS[0..3]
    0x57: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),       # NOS[0] <= r0
    0x58: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),       # NOS[1] <= final r1
    0x59: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),      # NOS[2] <= P11_LO
    0x5A: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),   # NOS[3] <= P11_HI

    # --- OP_DIV (0x60 - 0x73) --- Reciprocal Multiplication via Flash
    0x60: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_OPB, SEQ_NEXT),         # OPB <= TOS[0] (Divisor)
    0x61: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_ACC, SEQ_NEXT),         # ACC <= NOS[0] (Dividend)
    0x62: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_RD_FLASH_REC, LD_TMP0_LO, SEQ_NEXT), # TMP0_LO <= Recip[OPB]_LO
    0x63: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_RD_FLASH_REC, LD_TMP0_HI, SEQ_NEXT), # TMP0_HI <= Recip[OPB]_HI
    0x64: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1, SEQ_NEXT),           # TMP1 <= ACC
    0x65: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_NOP, LD_OPB, SEQ_NEXT),        # OPB <= TMP0_HI
    0x66: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),             # Partial product via QS
    0x67: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1, SEQ_NEXT),
    0x68: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),
    0x69: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT),
    0x6A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0_LO, SEQ_NEXT),
    0x6B: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),
    0x6C: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT),
    0x6D: (ALU_PASS_X, MUX_OPB, MUX_OPB, MEM_NOP, LD_TMP1_LO, SEQ_NEXT),
    0x6E: (ALU_SUB, MUX_TMP0, MUX_TMP1, MEM_NOP, LD_TMP0, SEQ_NEXT),           # Quotient
    0x6F: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),
    0x70: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),      # Write Quotient LO -> NOS[0]
    0x71: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[1]
    0x72: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[2]
    0x73: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_SQRT_INT (0x80 - 0x86) --- Integer Square Root
    0x80: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x81: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SQRT, LD_TMP0_LO, SEQ_NEXT),
    0x82: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SQRT, LD_TMP0_HI, SEQ_NEXT),
    0x83: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),       # TMP0_LO <= seed_hi
    0x84: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write integer sqrt -> NOS[0]
    0x85: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[1]
    0x86: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Pad upper bytes

    # --- OP_SQRT_FX (0x88 - 0x8E) --- Fixed-Point 16.16 Square Root
    0x88: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x89: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SQRT, LD_TMP0_LO, SEQ_NEXT),
    0x8A: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SQRT, LD_TMP0_HI, SEQ_NEXT),
    0x8B: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x8C: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x8D: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x8E: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_LOG2 (0x90 - 0x96) --- Base-2 Logarithm Table Lookup
    0x90: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0x91: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG2, LD_TMP0_LO, SEQ_NEXT),
    0x92: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG2, LD_TMP0_HI, SEQ_NEXT),
    0x93: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0x94: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0x95: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0x96: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_EXP (0xA0 - 0xA6) --- Base-2 Exponential Table Lookup
    0xA0: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0xA1: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_EXP2, LD_TMP0_LO, SEQ_NEXT),
    0xA2: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_EXP2, LD_TMP0_HI, SEQ_NEXT),
    0xA3: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0xA4: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0xA5: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0xA6: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_POW (0xB0 - 0xC2) --- General Power Function
    0xB0: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0xB1: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG2, LD_TMP0_LO, SEQ_NEXT),
    0xB2: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG2, LD_TMP0_HI, SEQ_NEXT),
    0xB3: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_NOS, LD_OPB, SEQ_NEXT),
    0xB4: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_NOP, LD_ACC, SEQ_NEXT),
    0xB5: (ALU_ADD, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP1, SEQ_NEXT),
    0xB6: (ALU_ABS_DIFF, MUX_ACC, MUX_OPB, MEM_NOP, LD_TMP0, SEQ_NEXT),
    0xB7: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_ACC, SEQ_NEXT),
    0xB8: (ALU_PASS_X, MUX_TMP1, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP1_HI, SEQ_NEXT),
    0xB9: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_OPB, SEQ_NEXT),
    0xBA: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_RD_FLASH_QS, LD_TMP0_HI, SEQ_NEXT),
    0xBB: (ALU_SUB, MUX_TMP1, MUX_TMP0, MEM_NOP, LD_TMP1, SEQ_NEXT),
    0xBC: (ALU_SWAP_BYTES, MUX_TMP1, MUX_OPB, MEM_NOP, LD_ACC, SEQ_NEXT),
    0xBD: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_EXP2, LD_TMP0_LO, SEQ_NEXT),
    0xBE: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_EXP2, LD_TMP0_HI, SEQ_NEXT),
    0xBF: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0xC0: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0xC1: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),    # Write seed_hi -> NOS[2]
    0xC2: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),     # Write 00 -> NOS[3]

    # --- OP_SIN (0xC8 - 0xCD) --- Sine Table Lookup
    0xC8: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0xC9: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SIN, LD_TMP0_LO, SEQ_NEXT),
    0xCA: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_SIN, LD_TMP0_HI, SEQ_NEXT),
    0xCB: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0xCD: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0xCE: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),    # Write seed_hi -> NOS[2]

    # --- OP_COS (0xD0 - 0xD5) --- Cosine Table Lookup
    0xD0: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0xD1: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_COS, LD_TMP0_LO, SEQ_NEXT),
    0xD2: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_COS, LD_TMP0_HI, SEQ_NEXT),
    0xD3: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0xD4: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0xD5: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),    # Write seed_hi -> NOS[2]

    # --- OP_TAN (0xD8 - 0xDD) --- Tangent Table Lookup
    0xD8: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0xD9: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_TAN, LD_TMP0_LO, SEQ_NEXT),
    0xDA: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_TAN, LD_TMP0_HI, SEQ_NEXT),
    0xDB: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0xDC: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0xDD: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),    # Write seed_hi -> NOS[2]

    # --- OP_LN (0xE0 - 0xE5) --- Natural Log Table Lookup
    0xE0: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0xE1: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LN, LD_TMP0_LO, SEQ_NEXT),
    0xE2: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LN, LD_TMP0_HI, SEQ_NEXT),
    0xE3: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0xE4: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0xE5: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),    # Write seed_hi -> NOS[2]

    # --- OP_LOG10 (0xE8 - 0xED) --- Base-10 Log Table Lookup
    0xE8: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_ACC, SEQ_NEXT),
    0xE9: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG10, LD_TMP0_LO, SEQ_NEXT),
    0xEA: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_FLASH_LOG10, LD_TMP0_HI, SEQ_NEXT),
    0xEB: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),     # Write 00 -> NOS[0]
    0xEC: (ALU_PASS_X, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_NEXT),        # Write seed_lo -> NOS[1]
    0xED: (ALU_SWAP_BYTES, MUX_TMP0, MUX_OPB, MEM_WR_NOS, LD_NONE, SEQ_DONE),    # Write seed_hi -> NOS[2]

    # --- OP_CHS (0xF0 - 0xF4) --- Two's Complement Negation Loop
    0xF0: (ALU_PASS_ZERO, MUX_ACC, MUX_OPB, MEM_NOP, LD_ACC, SEQ_NEXT),          # ACC <= 0
    0xF1: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_RD_TOS, LD_OPB, SEQ_NEXT),         # OPB <= SRAM[TOS + byte_cnt]
    0xF2: (ALU_SUB, MUX_ACC, MUX_OPB, MEM_WR_TOS, LD_NONE, SEQ_NEXT),            # SRAM[NOS] <= ACC (0) - OPB - carry
    0xF3: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_LOOP),           # Loop on BYTE_CNT
    0xF4: (ALU_PASS_X, MUX_ACC, MUX_OPB, MEM_NOP, LD_NONE, SEQ_DONE),
}