"""Auto-generated by tools/build_flash.py - DO NOT EDIT MANUALLY.

FPU Tables Base Addresses and Word Slot Maps for EBR / Flash ROM.
"""

from enum import IntEnum


class FpuTables(IntEnum):
    """Flash ROM Table Base Byte Addresses."""
    RECIP = 0x0400  # Reciprocal Table (512 bytes)
    SQRT = 0x0600  # Square Root Seed Table (512 bytes)
    EXP2 = 0x0800  # Exp2 Table (512 bytes)
    LOG2 = 0x0A00  # Log2 Table (512 bytes)
    SIN = 0x0C00  # Sine Table (512 bytes)
    COS = 0x0E00  # Cosine Table (512 bytes)
    TAN = 0x1000  # Tangent Table (512 bytes)
    LN = 0x1200  # Natural Log Table (512 bytes)
    LOG10 = 0x1400  # Base-10 Log Table (512 bytes)
    CONST = 0x1600  # Mathematical Constants Table (256 bytes)
    CORDIC_ATAN32 = 0x1800  # CORDIC Arctangent 32-bit Table (128 bytes)
    CORDIC_ATAN64 = 0x1900  # CORDIC Arctangent 64-bit Table (512 bytes)
    TRIG_CONST = 0x1B00  # Trigonometric & CORDIC Constants (128 bytes)
    CHEB = 0x1C00  # Chebyshev & Polynomial Coefficients Table (512 bytes)


class FpuTable(IntEnum):
    """4-bit Table Identifier for LDC instruction (MicroOp.LDC).

    Mapped to physical EBR and base offset in memory controller:
      - RECIP: EBR 4 (16-bit), base 0x000 (words 0..255)
      - SQRT:  EBR 4 (16-bit), base 0x100 (words 256..511)
      - TRIG:  EBR 2 & 3 (paired 32-bit), base 0x000 (words 0..127)
      - CHEB:  EBR 2 & 3 (paired 32-bit), base 0x080 (words 128..255)
      - CONST: EBR 2 & 3 (paired 32-bit), base 0x100 (words 256..319)
    """
    RECIP = 0b000  # 0: EBR 4 (16-bit), base 0x000 (words 0..255)
    SQRT = 0b001   # 1: EBR 4 (16-bit), base 0x100 (words 256..511)
    TRIG = 0b100   # 4: EBR 2 & 3 (paired 32-bit), base 0x000 (words 0..127)
    CHEB = 0b101   # 5: EBR 2 & 3 (paired 32-bit), base 0x080 (words 128..255)
    CONST = 0b110  # 6: EBR 2 & 3 (paired 32-bit), base 0x100 (words 256..319)


class FpuCheb(IntEnum):
    """Chebyshev / Polynomial Coefficients Word Slot Map for EBR CHEB ROM.
    Each slot represents a 32-bit word offset from CHEB table base (EBR 2/3 offset 0x080).
    """
    EXP2_C1 = 1  # exp2 Taylor c1 (ln(2) in Q1.31)
    EXP2_C2 = 2  # exp2 Taylor c2 (ln(2)^2 / 2 in Q1.31)
    EXP2_C3 = 3  # exp2 Taylor c3 (ln(2)^3 / 6 in Q1.31)
    EXP2_C4 = 4  # exp2 Taylor c4 (ln(2)^4 / 24 in Q1.31)
    EXP2_C5 = 5  # exp2 Taylor c5 (ln(2)^5 / 120 in Q1.31)
    EXP2_C6 = 6  # exp2 Taylor c6 (ln(2)^6 / 720 in Q1.31)
    LOG2_C0 = 7  # log2 minimax c0 (2.88539008 in Q3.29)
    LOG2_C1 = 8  # log2 minimax c1 (0.96179840 in Q3.29)
    LOG2_C2 = 9  # log2 minimax c2 (0.57676343 in Q3.29)
    LOG2_C3 = 10  # log2 minimax c3 (0.43044988 in Q3.29)
    SQRT2_MANT = 11  # sqrt(2) mantissa threshold (bit 23 implicit 1)


class FpuConst(IntEnum):
    """FPU Constants Word Slot Map for EBR Constants ROM.
    Each slot represents a 32-bit word offset from CONST table base (EBR 2/3 offset 0x100).
    """
    PI_F32 = 0  # pi in IEEE-754 single precision
    PI_F64 = 2  # pi in IEEE-754 double precision
    E_F32 = 4  # e in IEEE-754 single precision
    E_F64 = 6  # e in IEEE-754 double precision
    LN2_F32 = 8  # ln(2) in IEEE-754 single precision
    LN2_F64 = 10  # ln(2) in IEEE-754 double precision
    LOG2E_F32 = 12  # log2(e) in IEEE-754 single precision
    LOG2E_F64 = 14  # log2(e) in IEEE-754 double precision
    LOG2_10_F32 = 16  # log2(10) in IEEE-754 single precision
    LOG2_10_F64 = 18  # log2(10) in IEEE-754 double precision
    LOG10_2_F32 = 20  # log10(2) in IEEE-754 single precision
    LOG10_2_F64 = 22  # log10(2) in IEEE-754 double precision
    SQRT2_F32 = 24  # sqrt(2) in IEEE-754 single precision
    SQRT2_F64 = 26  # sqrt(2) in IEEE-754 double precision
    INV_SQRT2_F32 = 28  # 1/sqrt(2) in IEEE-754 single precision
    INV_SQRT2_F64 = 30  # 1/sqrt(2) in IEEE-754 double precision
    ONE_F32 = 32  # 1.0 in IEEE-754 single precision
    ONE_F64 = 33  # 1.0 in IEEE-754 double precision
    NAN_F32 = 35  # Quiet NaN in IEEE-754 single precision
    NAN_F64 = 36  # Quiet NaN in IEEE-754 double precision
    POS_INF_F32 = 38  # +Infinity in IEEE-754 single precision
    NEG_INF_F32 = 39  # -Infinity in IEEE-754 single precision
    POS_INF_F64 = 40  # +Infinity in IEEE-754 double precision
    NEG_INF_F64 = 42  # -Infinity in IEEE-754 double precision
    TWO_OVER_PI_F32 = 44  # 2/pi in IEEE-754 single precision
    TWO_OVER_PI_F64 = 45  # 2/pi in IEEE-754 double precision
    CW_C1_F32 = 47  # Cody-Waite C1 in IEEE-754 single precision
    CW_C2_F32 = 48  # Cody-Waite C2 in IEEE-754 single precision
    CW_C1_F64 = 49  # Cody-Waite C1 in IEEE-754 double precision
    CW_C2_F64 = 51  # Cody-Waite C2 in IEEE-754 double precision
    CW_C3_F64 = 53  # Cody-Waite C3 in IEEE-754 double precision
    CORDIC_INV_K_32 = 55  # CORDIC 1/K scale factor in Q2.30
    CORDIC_INV_K_64 = 56  # CORDIC 1/K scale factor in Q2.62
    LN10_F32 = 58  # ln(10) in IEEE-754 single precision
    LN10_F64 = 60  # ln(10) in IEEE-754 double precision


