"""Auto-generated by tools/build_flash.py - DO NOT EDIT MANUALLY.

FPU Tables Base Addresses and Word Slot Maps for EBR / Flash ROM.
"""

from enum import IntEnum


class FpuTables(IntEnum):
    """Flash ROM Image Base Byte Addresses."""
    DATA_RAM = 0x0000  # DATA_RAM Image (4096 bytes, Words 0..1023)
    CODE_ROM = 0x1000  # CODE_ROM Image (4096 bytes, Words 1024..2047)


class FpuTable(IntEnum):
    """Table Identifier for LDC instruction (MicroOp.LDC).

    Mapped to base offsets in unified DATA_RAM (1024x32, EBR 0):
      - CONST: Base 0x100 (words 256..319, 32-bit)
      - TRIG:  Base 0x200 (words 512..639, 32-bit)
      - CHEB:  Base 0x280 (words 640..767, 32-bit)
      - RECIP: Base 0x300 (words 768..1023, low 16-bit slice)
      - SQRT:  Base 0x300 (words 768..1023, high 16-bit slice)
    """
    CONST = 0
    TRIG = 1
    CHEB = 2
    RECIP = 3
    SQRT = 4


class FpuCheb(IntEnum):
    """Chebyshev / Polynomial Coefficients Word Slot Map for EBR CHEB ROM.
    Each slot represents a 32-bit word offset from CHEB table base (0x280).
    """
    EXP2_C1 = 1  # exp2 Taylor c1 (ln(2) in Q1.31)
    EXP2_C2 = 2  # exp2 Taylor c2 (ln(2)^2 / 2 in Q1.31)
    EXP2_C3 = 3  # exp2 Taylor c3 (ln(2)^3 / 6 in Q1.31)
    EXP2_C4 = 4  # exp2 Taylor c4 (ln(2)^4 / 24 in Q1.31)
    EXP2_C5 = 5  # exp2 Taylor c5 (ln(2)^5 / 120 in Q1.31)
    EXP2_C6 = 6  # exp2 Taylor c6 (ln(2)^6 / 720 in Q1.31)
    LOG2_C0 = 7  # log2 minimax c0 (2.88539008 in Q3.29)
    LOG2_C1 = 8  # log2 minimax c1 (0.96179840 in Q3.29)
    LOG2_C2 = 9  # log2 minimax c2 (0.57676343 in Q3.29)
    LOG2_C3 = 10  # log2 minimax c3 (0.43044988 in Q3.29)
    SQRT2_MANT = 11  # sqrt(2) mantissa threshold (bit 23 implicit 1)


class FpuConst(IntEnum):
    """FPU Constants Word Slot Map for EBR Constants ROM.
    Each slot represents a 32-bit word offset from CONST table base (0x100).
    """
    PI_F32 = 0  # pi in IEEE-754 single precision
    PI_F64 = 2  # pi in IEEE-754 double precision
    E_F32 = 4  # e in IEEE-754 single precision
    E_F64 = 6  # e in IEEE-754 double precision
    LN2_F32 = 8  # ln(2) in IEEE-754 single precision
    LN2_F64 = 10  # ln(2) in IEEE-754 double precision
    LOG2E_F32 = 12  # log2(e) in IEEE-754 single precision
    LOG2E_F64 = 14  # log2(e) in IEEE-754 double precision
    LOG2_10_F32 = 16  # log2(10) in IEEE-754 single precision
    LOG2_10_F64 = 18  # log2(10) in IEEE-754 double precision
    LOG10_2_F32 = 20  # log10(2) in IEEE-754 single precision
    LOG10_2_F64 = 22  # log10(2) in IEEE-754 double precision
    SQRT2_F32 = 24  # sqrt(2) in IEEE-754 single precision
    SQRT2_F64 = 26  # sqrt(2) in IEEE-754 double precision
    INV_SQRT2_F32 = 28  # 1/sqrt(2) in IEEE-754 single precision
    INV_SQRT2_F64 = 30  # 1/sqrt(2) in IEEE-754 double precision
    ONE_F32 = 32  # 1.0 in IEEE-754 single precision
    ONE_F64 = 33  # 1.0 in IEEE-754 double precision
    NAN_F32 = 35  # Quiet NaN in IEEE-754 single precision
    NAN_F64 = 36  # Quiet NaN in IEEE-754 double precision
    POS_INF_F32 = 38  # +Infinity in IEEE-754 single precision
    NEG_INF_F32 = 39  # -Infinity in IEEE-754 single precision
    POS_INF_F64 = 40  # +Infinity in IEEE-754 double precision
    NEG_INF_F64 = 42  # -Infinity in IEEE-754 double precision
    TWO_OVER_PI_F32 = 44  # 2/pi in IEEE-754 single precision
    TWO_OVER_PI_F64 = 45  # 2/pi in IEEE-754 double precision
    CW_C1_F32 = 47  # Cody-Waite C1 in IEEE-754 single precision
    CW_C2_F32 = 48  # Cody-Waite C2 in IEEE-754 single precision
    CW_C1_F64 = 49  # Cody-Waite C1 in IEEE-754 double precision
    CW_C2_F64 = 51  # Cody-Waite C2 in IEEE-754 double precision
    CW_C3_F64 = 53  # Cody-Waite C3 in IEEE-754 double precision
    CORDIC_INV_K_32 = 55  # CORDIC 1/K scale factor in Q2.30
    CORDIC_INV_K_64 = 56  # CORDIC 1/K scale factor in Q2.62
    LN10_F32 = 58  # ln(10) in IEEE-754 single precision
    LN10_F64 = 60  # ln(10) in IEEE-754 double precision


