"""Auto-generated by tools/build_flash.py - DO NOT EDIT MANUALLY.

FPU Constants Word Slot Map for EBR Constants ROM.
Each slot represents a 32-bit word offset from FLASH_CONST_BASE.
Byte address in ROM = FLASH_CONST_BASE + (slot << 2).
"""

from enum import IntEnum


class FpuConst(IntEnum):
    PI_F32 = 0  # pi in IEEE-754 single precision
    PI_F64 = 2  # pi in IEEE-754 double precision
    E_F32 = 4  # e in IEEE-754 single precision
    E_F64 = 6  # e in IEEE-754 double precision
    LN2_F32 = 8  # ln(2) in IEEE-754 single precision
    LN2_F64 = 10  # ln(2) in IEEE-754 double precision
    LOG2E_F32 = 12  # log2(e) in IEEE-754 single precision
    LOG2E_F64 = 14  # log2(e) in IEEE-754 double precision
    LOG2_10_F32 = 16  # log2(10) in IEEE-754 single precision
    LOG2_10_F64 = 18  # log2(10) in IEEE-754 double precision
    LOG10_2_F32 = 20  # log10(2) in IEEE-754 single precision
    LOG10_2_F64 = 22  # log10(2) in IEEE-754 double precision
    SQRT2_F32 = 24  # sqrt(2) in IEEE-754 single precision
    SQRT2_F64 = 26  # sqrt(2) in IEEE-754 double precision
    INV_SQRT2_F32 = 28  # 1/sqrt(2) in IEEE-754 single precision
    INV_SQRT2_F64 = 30  # 1/sqrt(2) in IEEE-754 double precision
    ONE_F32 = 32  # 1.0 in IEEE-754 single precision
    ONE_F64 = 33  # 1.0 in IEEE-754 double precision
    NAN_F32 = 35  # Quiet NaN in IEEE-754 single precision
    NAN_F64 = 36  # Quiet NaN in IEEE-754 double precision
    POS_INF_F32 = 38  # +Infinity in IEEE-754 single precision
    NEG_INF_F32 = 39  # -Infinity in IEEE-754 single precision
    POS_INF_F64 = 40  # +Infinity in IEEE-754 double precision
    NEG_INF_F64 = 42  # -Infinity in IEEE-754 double precision
    TWO_OVER_PI_F32 = 44  # 2/pi in IEEE-754 single precision
    TWO_OVER_PI_F64 = 45  # 2/pi in IEEE-754 double precision
    CW_C1_F32 = 47  # Cody-Waite C1 in IEEE-754 single precision
    CW_C2_F32 = 48  # Cody-Waite C2 in IEEE-754 single precision
    CW_C1_F64 = 49  # Cody-Waite C1 in IEEE-754 double precision
    CW_C2_F64 = 51  # Cody-Waite C2 in IEEE-754 double precision
    CW_C3_F64 = 53  # Cody-Waite C3 in IEEE-754 double precision
    CORDIC_INV_K_32 = 55  # CORDIC 1/K scale factor in Q2.30
    CORDIC_INV_K_64 = 56  # CORDIC 1/K scale factor in Q2.62

