import struct
from pathlib import Path
import pytest
from fpu_asm.__main__ import main
from fpu_asm.emitter import (
    pad_instructions,
    emit_binary,
    emit_hex,
    emit_python,
    emit_symbols,
    write_output,
    write_symbol_table,
    create_nop_instruction,
)
from fpu_emu.micro_instruction import MicroInstruction, IW
from fpu_emu.micro_opcodes import MicroOp
from fpu_emu.hardware.reg import Reg
from fpu_emu.hardware.register import StatusFlag
from fpu_emu.rom.fpu_const_map import FpuTable


def test_pad_instructions_default_512():
    inst0 = MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL)
    inst2 = MicroInstruction(op=MicroOp.HALT)
    instructions = [(0, inst0), (2, inst2)]

    padded = pad_instructions(instructions)
    assert len(padded) == 512
    assert padded[0] == inst0
    assert padded[1].op == MicroOp.NOP
    assert padded[2] == inst2
    for i in range(3, 512):
        assert padded[i].op == MicroOp.NOP


def test_pad_instructions_no_pad():
    inst0 = MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL)
    inst2 = MicroInstruction(op=MicroOp.HALT)
    instructions = [(0, inst0), (2, inst2)]

    padded = pad_instructions(instructions, total_words=None)
    assert len(padded) == 3
    assert padded[0] == inst0
    assert padded[1].op == MicroOp.NOP
    assert padded[2] == inst2


def test_pad_instructions_duplicate_address():
    inst0 = MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL)
    inst1 = MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL)
    instructions = [(0, inst0), (0, inst1)]

    with pytest.raises(ValueError, match="Multiple instructions defined"):
        pad_instructions(instructions)


def test_pad_instructions_negative_address():
    inst = MicroInstruction(op=MicroOp.HALT)
    with pytest.raises(ValueError, match="Invalid negative address"):
        pad_instructions([(-1, inst)])


def test_emit_binary_and_hex():
    nop = create_nop_instruction()
    instructions = [nop, nop]

    raw_bin = emit_binary(instructions)
    assert len(raw_bin) == 8  # 2 words * 4 bytes
    assert raw_bin == nop.to_bytes() + nop.to_bytes()

    hex_str = emit_hex(instructions)
    hex_lines = hex_str.strip().splitlines()
    assert len(hex_lines) == 2
    assert hex_lines[0] == f"{nop.to_int():08X}"
    assert hex_lines[1] == f"{nop.to_int():08X}"


def test_emit_python():
    insts = [
        MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
        MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=6),
        MicroInstruction(op=MicroOp.LDC, dst=Reg.AL, src=FpuTable.CONST, imm=1),
        MicroInstruction(op=MicroOp.HALT),
    ]
    syms = {
        "User_ADD_I32": 0,
        "User_SUB_I32": 2,
        "LOOP_START": 1,
    }

    py_str = emit_python(insts, symbols=syms)
    assert "DO NOT EDIT. GENERATED BY fpu_asm" in py_str
    assert "# User_ADD_I32" in py_str
    assert "# User_SUB_I32" in py_str

    # Ensure it's valid executable Python
    namespace = {}
    exec(py_str, namespace)

    assert "fpu_ucode" in namespace
    assert "fpu_symbols" in namespace
    assert len(namespace["fpu_ucode"]) == 4
    assert namespace["fpu_ucode"][0].op == MicroOp.POP
    assert namespace["fpu_ucode"][1].flag == StatusFlag.UNDERFLOW

    # Only User_ symbols should be present in fpu_symbols, and sorted
    symbols_dict = namespace["fpu_symbols"]
    assert list(symbols_dict.keys()) == ["User_ADD_I32", "User_SUB_I32"]
    assert symbols_dict["User_ADD_I32"] == 0
    assert symbols_dict["User_SUB_I32"] == 2
    assert "LOOP_START" not in symbols_dict


def test_emit_symbols():
    syms = {
        "User_SUB_I32": 10,
        "User_ADD_I32": 0,
        "LOCAL_LABEL": 5,
        "ANOTHER_LABEL": 2,
    }

    sym_str = emit_symbols(syms)
    assert "[USER_SYMBOLS]" in sym_str
    assert "[OTHER_SYMBOLS]" in sym_str

    user_part, other_part = sym_str.split("[OTHER_SYMBOLS]")
    # User symbols should be sorted within section
    assert user_part.index("User_ADD_I32") < user_part.index("User_SUB_I32")
    # Other symbols should be sorted within section
    assert other_part.index("ANOTHER_LABEL") < other_part.index("LOCAL_LABEL")


def test_write_output_auto(tmp_path: Path):
    nop = create_nop_instruction()
    bin_file = tmp_path / "out.bin"
    write_output([nop], bin_file)
    assert bin_file.exists()
    assert bin_file.read_bytes() == nop.to_bytes()

    hex_file = tmp_path / "out.hex"
    write_output([nop], hex_file)
    assert hex_file.exists()
    assert hex_file.read_text(encoding="ascii").strip() == f"{nop.to_int():08X}"

    py_file = tmp_path / "out.py"
    write_output([nop], py_file, symbols={"User_TEST": 0})
    assert py_file.exists()
    ns = {}
    exec(py_file.read_text(encoding="utf-8"), ns)
    assert ns["fpu_symbols"] == {"User_TEST": 0}


def test_cli_main_success_bin(tmp_path: Path, capsys):
    asm_file = tmp_path / "code.fasm"
    asm_file.write_text("ADD AL, BL\nHALT\n", encoding="utf-8")
    bin_file = tmp_path / "code.bin"

    ret = main(["-i", str(asm_file), "-o", str(bin_file)])
    assert ret == 0
    assert bin_file.exists()
    # 512 words * 4 bytes = 2048 bytes
    assert len(bin_file.read_bytes()) == 512 * 4

    captured = capsys.readouterr()
    assert "Successfully assembled 2 instructions (padded to 512 words)" in captured.out


def test_cli_main_success_python_and_sym(tmp_path: Path, capsys):
    asm_file = tmp_path / "code.fasm"
    asm_file.write_text(
        "User_ADD_I32:\n"
        "    ADD AL, BL\n"
        "LOOP_END:\n"
        "    HALT\n",
        encoding="utf-8",
    )
    py_file = tmp_path / "code.py"
    sym_file = tmp_path / "code.sym"

    ret = main([
        "-i", str(asm_file),
        "-o", str(py_file),
        "-s", str(sym_file),
        "--no-pad",
    ])
    assert ret == 0
    assert py_file.exists()
    assert sym_file.exists()

    # Verify python output
    ns = {}
    exec(py_file.read_text(encoding="utf-8"), ns)
    assert len(ns["fpu_ucode"]) == 2
    assert ns["fpu_symbols"] == {"User_ADD_I32": 0}

    # Verify sym output
    sym_content = sym_file.read_text(encoding="utf-8")
    assert "[USER_SYMBOLS]" in sym_content
    assert "User_ADD_I32" in sym_content
    assert "[OTHER_SYMBOLS]" in sym_content
    assert "LOOP_END" in sym_content


def test_cli_main_file_not_found(capsys):
    ret = main(["-i", "does_not_exist.fasm", "-o", "out.bin"])
    assert ret == 1
    captured = capsys.readouterr()
    assert "Error: Input file 'does_not_exist.fasm' not found." in captured.err


def test_cli_main_syntax_error(tmp_path: Path, capsys):
    asm_file = tmp_path / "bad.fasm"
    asm_file.write_text("SYNTAX ERROR\n", encoding="utf-8")
    bin_file = tmp_path / "bad.bin"

    ret = main(["-i", str(asm_file), "-o", str(bin_file)])
    assert ret == 1
    captured = capsys.readouterr()
    assert "Assembly Error:" in captured.err
    assert "bad.fasm:1:" in captured.err
