"""Auto-generated microcode and symbol table module by fpu_asm."""

from typing import Dict, List
from fpu_emu.hardware.reg import Reg
from fpu_emu.hardware.register import StatusFlag
from fpu_emu.micro_instruction import MicroInstruction, IW
from fpu_emu.micro_opcodes import MicroOp
from fpu_emu.rom.fpu_const_map import FpuTable


fpu_ucode: List[MicroInstruction] = [
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=48),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DL, src=Reg.BL),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=48),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EB, src=Reg.BL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=42),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=44),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=16),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.ZERO, imm=19),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=16),
    MicroInstruction(op=MicroOp.JMP, imm=19),
    MicroInstruction(op=MicroOp.SWAP, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.SWAP, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.DL),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.C, src1=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=32),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=24),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JMP, imm=25),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.BL, src=Reg.C),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.DIFF_SIGN, imm=28),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JMP, imm=29),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LZC, dst=Reg.C, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=46),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=38),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=40),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.C),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.C),
    MicroInstruction(op=MicroOp.JMP, imm=40),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.DL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JMP, imm=42),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=55),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=55),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=62),
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=62),
    MicroInstruction(op=MicroOp.ADD, w=IW.W64, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=112),
    MicroInstruction(op=MicroOp.FCHS, dst=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DL, src=Reg.BL),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=112),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EB, src=Reg.BL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=106),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=108),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=80),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.ZERO, imm=83),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=80),
    MicroInstruction(op=MicroOp.JMP, imm=83),
    MicroInstruction(op=MicroOp.SWAP, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.SWAP, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.DL),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.C, src1=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=32),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=88),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JMP, imm=89),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.BL, src=Reg.C),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.DIFF_SIGN, imm=92),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JMP, imm=93),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LZC, dst=Reg.C, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=110),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=102),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=104),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.C),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.C),
    MicroInstruction(op=MicroOp.JMP, imm=104),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.DL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JMP, imm=106),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=119),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=119),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=126),
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=126),
    MicroInstruction(op=MicroOp.SUB, w=IW.W64, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
    MicroInstruction(op=MicroOp.NOP),
]

# Only needs to include the instruction line of the "User_" symbols, sort them when writing to the file.
fpu_symbols: Dict[str, int] = {
    "USER_ADD_F32": 0,
    "USER_ADD_I32": 49,
    "USER_ADD_I64": 56,
    "USER_SUB_F32": 63,
    "USER_SUB_I32": 113,
    "USER_SUB_I64": 120,
}
