"""Auto-generated microcode and symbol table module by fpu_asm."""

from typing import Dict, List
from fpu_emu.hardware.reg import Reg
from fpu_emu.hardware.register import StatusFlag
from fpu_emu.micro_instruction import MicroInstruction, IW
from fpu_emu.micro_opcodes import MicroOp
from fpu_emu.rom.fpu_const_map import FpuTable


fpu_ucode: List[MicroInstruction] = [
    # USER_ADD_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=48),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DL, src=Reg.BL),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=48),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EB, src=Reg.BL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=42),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=44),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=16),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.ZERO, imm=19),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=16),
    MicroInstruction(op=MicroOp.JMP, imm=19),
    MicroInstruction(op=MicroOp.SWAP, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.SWAP, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.DL),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.C, src1=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=32),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=24),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JMP, imm=25),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.BL, src=Reg.C),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.DIFF_SIGN, imm=28),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JMP, imm=29),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LZC, dst=Reg.C, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=46),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=38),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=40),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.C),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.C),
    MicroInstruction(op=MicroOp.JMP, imm=40),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.DL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JMP, imm=42),
    MicroInstruction(op=MicroOp.HALT),

    # USER_ADD_I32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=55),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=55),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_ADD_I64
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=62),
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=62),
    MicroInstruction(op=MicroOp.ADD, w=IW.W64, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_SUB_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=112),
    MicroInstruction(op=MicroOp.FCHS, dst=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DL, src=Reg.BL),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=112),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EB, src=Reg.BL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=106),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=108),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=80),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.ZERO, imm=83),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=80),
    MicroInstruction(op=MicroOp.JMP, imm=83),
    MicroInstruction(op=MicroOp.SWAP, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.SWAP, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.DL),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.C, src1=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=32),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=88),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JMP, imm=89),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.BL, src=Reg.C),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.DIFF_SIGN, imm=92),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JMP, imm=93),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LZC, dst=Reg.C, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=110),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=102),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=104),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.C),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.C),
    MicroInstruction(op=MicroOp.JMP, imm=104),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.DL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JMP, imm=106),
    MicroInstruction(op=MicroOp.HALT),

    # USER_SUB_I32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=119),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=119),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_SUB_I64
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=126),
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=126),
    MicroInstruction(op=MicroOp.SUB, w=IW.W64, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_MUL_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=153),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=153),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BH, src=Reg.AL),
    MicroInstruction(op=MicroOp.XOR, dst=Reg.BH, src=Reg.BL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EB, src=Reg.BL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=151),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=151),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LSR, w=IW.W64, dst=Reg.AL, src=Reg.IMM, imm=23),
    MicroInstruction(op=MicroOp.LZC, dst=Reg.C, src=Reg.AL),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=145),
    MicroInstruction(op=MicroOp.JMP, imm=147),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.OR, dst=Reg.BH, src=Reg.BH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JMP, imm=147),
    MicroInstruction(op=MicroOp.HALT),

    # USER_MUL_I32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=160),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=160),
    MicroInstruction(op=MicroOp.MUL, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_MUL_I64
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=182),
    MicroInstruction(op=MicroOp.STO, w=IW.W64, src=Reg.BL),
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=182),
    MicroInstruction(op=MicroOp.STO, w=IW.W64, src=Reg.AL, imm=2),
    MicroInstruction(op=MicroOp.LD, dst=Reg.BL, imm=1),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=4),
    MicroInstruction(op=MicroOp.LD, dst=Reg.AL, imm=3),
    MicroInstruction(op=MicroOp.LD, dst=Reg.BL),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LD, dst=Reg.BL, imm=4),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=4),
    MicroInstruction(op=MicroOp.LD, dst=Reg.AL, imm=2),
    MicroInstruction(op=MicroOp.LD, dst=Reg.BL),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LD, dst=Reg.BL, imm=4),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_DIV_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=219),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=219),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BH, src=Reg.AL),
    MicroInstruction(op=MicroOp.XOR, dst=Reg.BH, src=Reg.BL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EB, src=Reg.BL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=216),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=214),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.LZC, dst=Reg.C, src=Reg.AL),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=220),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.JMP, imm=221),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JMP, imm=221),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.BL, src=Reg.BL),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.OR, dst=Reg.BH, src=Reg.BH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_DIV_I32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=232),
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=232),
    MicroInstruction(op=MicroOp.DIV, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.ERR, imm=232),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_SQRT_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=287),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BH, src=Reg.AL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=288),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.SIGN, imm=290),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=255),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=288),
    MicroInstruction(op=MicroOp.AND, dst=Reg.BL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=251),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DL, src=Reg.AL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.DL, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AL),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.BL, src=Reg.IMM, imm=16),
    MicroInstruction(op=MicroOp.AND, dst=Reg.BL, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.JMP, imm=258),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DL, src=Reg.AL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.DL, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AL),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.BL, src=Reg.IMM, imm=16),
    MicroInstruction(op=MicroOp.AND, dst=Reg.BL, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.OR, dst=Reg.BL, src=Reg.IMM, imm=128),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=126),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.FL, src=Reg.EA),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.FL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.EA, src=Reg.FL),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.AH, src1=Reg.BL, src=FpuTable.SQRT, imm=0),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=16),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AH),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.DH, src=Reg.IMM, imm=3),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.DH, src=Reg.IMM, imm=30),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.C, src=Reg.IMM, imm=2),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BH, src=Reg.DH),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.BH, src=Reg.AH),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.BH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=31),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AH),
    MicroInstruction(op=MicroOp.DJNZ, imm=267),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.IMM, imm=64),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AH, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AH, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AH),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.BH),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.LDI, src=Reg.IMM, flag=StatusFlag.ERR, imm=1),
    MicroInstruction(op=MicroOp.HALT),

    # USER_LOG2_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=408),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BH, src=Reg.AL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=406),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.SIGN, imm=406),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=255),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=404),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CONST, imm=32),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.BH),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=401),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=10),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=308),
    MicroInstruction(op=MicroOp.JMP, imm=310),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.BH, src=Reg.IMM, imm=23),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AL),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.BL, src=Reg.BH),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BH),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.C, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.SIGN, imm=318),
    MicroInstruction(op=MicroOp.JMP, imm=321),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.C, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.NOT, dst=Reg.AL),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=3),
    MicroInstruction(op=MicroOp.DIVU, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=3),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AH, src=Reg.AL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DH, src=Reg.AH),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DL, src=Reg.AH),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.AL, src1=Reg.IMM, src=FpuTable.CHEB, imm=3),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=2),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=1),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.DL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=0),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MULU, dst=Reg.AL, src=Reg.DH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AH, src=Reg.IMM, imm=6),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.C),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=373),
    MicroInstruction(op=MicroOp.NOT, dst=Reg.AH),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.EA, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=390),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=382),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BH, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.BL, src=Reg.IMM, imm=23),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.JMP, imm=409),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.BH, src=Reg.IMM, imm=31),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BL, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.BL, src=Reg.IMM, imm=23),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.BL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.JMP, imm=409),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BH, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AH),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=401),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.BL, src=Reg.IMM, imm=31),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=409),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.BH, src=Reg.IMM, imm=31),
    MicroInstruction(op=MicroOp.NOT, dst=Reg.AH),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.BH),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.LDI, src=Reg.IMM, flag=StatusFlag.ERR, imm=1),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.LZC, dst=Reg.BL, src=Reg.AH),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.EA, src=Reg.IMM, imm=135),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.BL),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.C, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.C, src=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.SIGN, imm=417),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AH, src=Reg.C),
    MicroInstruction(op=MicroOp.JMP, imm=420),
    MicroInstruction(op=MicroOp.NOT, dst=Reg.C),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.C, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.C),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.OR, dst=Reg.BH, src=Reg.BH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_EXP2_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=541),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BH, src=Reg.AL),
    MicroInstruction(op=MicroOp.UNPACK, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=526),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.C, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.SIGN, imm=433),
    MicroInstruction(op=MicroOp.JMP, imm=434),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.C, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=255),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=539),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.EA, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=451),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=7),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.CARRY, imm=448),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=448),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.C),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=532),
    MicroInstruction(op=MicroOp.JMP, imm=529),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.JMP, imm=454),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BL, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AL),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.BH, src=Reg.IMM, imm=22),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AL, src=Reg.BH),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AL, src=Reg.IMM, imm=23),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.EA, src=Reg.AL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AL, src=Reg.IMM, imm=23),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.BL, src=Reg.AL),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.BL, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BH, src=Reg.C),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BH, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=468),
    MicroInstruction(op=MicroOp.NOT, dst=Reg.BL),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.BL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.DH, src=Reg.BL),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.AL, src1=Reg.IMM, src=FpuTable.CHEB, imm=9),
    MicroInstruction(op=MicroOp.MUL, dst=Reg.AL, src=Reg.DH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=8),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MUL, dst=Reg.AL, src=Reg.DH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=7),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MUL, dst=Reg.AL, src=Reg.DH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=6),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MUL, dst=Reg.AL, src=Reg.DH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=5),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MUL, dst=Reg.AL, src=Reg.DH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.BL, src1=Reg.IMM, src=FpuTable.CHEB, imm=4),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.MUL, dst=Reg.AL, src=Reg.DH),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BL, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.BL, src=Reg.IMM, imm=31),
    MicroInstruction(op=MicroOp.ADD, dst=Reg.AH, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AH),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.BL, src=Reg.IMM, imm=31),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=507),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.EB, src=Reg.IMM, imm=127),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AH, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.JMP, imm=510),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.EB, src=Reg.IMM, imm=126),
    MicroInstruction(op=MicroOp.LSL, dst=Reg.AH, src=Reg.IMM, imm=1),
    MicroInstruction(op=MicroOp.LSR, dst=Reg.AH, src=Reg.IMM, imm=8),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.C),
    MicroInstruction(op=MicroOp.CMP, dst=Reg.BL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.ZERO, imm=517),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.EXP_SUB, dst=Reg.EA, src=Reg.BL),
    MicroInstruction(op=MicroOp.JMP, imm=520),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.EA),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.EA, src=Reg.EB),
    MicroInstruction(op=MicroOp.EXP_ADD, dst=Reg.EA, src=Reg.BL),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.AL, src=Reg.AH),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BH, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.OR, dst=Reg.BH, src=Reg.BH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.LDC, dst=Reg.AL, src1=Reg.IMM, src=FpuTable.CONST, imm=32),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.EA, src=Reg.IMM, imm=255),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.AL, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.LDI, dst=Reg.BH, src=Reg.IMM, imm=0),
    MicroInstruction(op=MicroOp.OR, dst=Reg.BH, src=Reg.BH),
    MicroInstruction(op=MicroOp.PACK, dst=Reg.AL, src=Reg.EA),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.BH),
    MicroInstruction(op=MicroOp.HALT),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CHS_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=546),
    MicroInstruction(op=MicroOp.FCHS, dst=Reg.AL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CHS_F64
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=551),
    MicroInstruction(op=MicroOp.FCHS, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CHS_I32
    MicroInstruction(op=MicroOp.POP, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=557),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CHS_I64
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.BL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=563),
    MicroInstruction(op=MicroOp.SUB, w=IW.W64, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.SUB, w=IW.W64, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_ABS_F32
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=568),
    MicroInstruction(op=MicroOp.FABS, dst=Reg.AL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_ABS_F64
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=573),
    MicroInstruction(op=MicroOp.FABS, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_ABS_I32
    MicroInstruction(op=MicroOp.POP, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=582),
    MicroInstruction(op=MicroOp.OR, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.SIGN, imm=581),
    MicroInstruction(op=MicroOp.MOV, dst=Reg.BL, src=Reg.AL),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.SUB, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_ABS_I64
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.AL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=591),
    MicroInstruction(op=MicroOp.OR, w=IW.W64, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.JZ, flag=StatusFlag.SIGN, imm=590),
    MicroInstruction(op=MicroOp.MOV, w=IW.W64, dst=Reg.BL, src=Reg.AL),
    MicroInstruction(op=MicroOp.SUB, w=IW.W64, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.SUB, w=IW.W64, dst=Reg.AL, src=Reg.BL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.AL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_DUP4
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=596),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_DUP8
    MicroInstruction(op=MicroOp.POP, w=IW.W64, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=601),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_PI_32
    MicroInstruction(op=MicroOp.LDC, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=0),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_PI_64
    MicroInstruction(op=MicroOp.LDC, w=IW.W64, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=2),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_E_32
    MicroInstruction(op=MicroOp.LDC, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=4),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_E_64
    MicroInstruction(op=MicroOp.LDC, w=IW.W64, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=6),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_LN2_32
    MicroInstruction(op=MicroOp.LDC, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=8),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_LN2_64
    MicroInstruction(op=MicroOp.LDC, w=IW.W64, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=10),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_LOG2E_32
    MicroInstruction(op=MicroOp.LDC, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=12),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_LOG2E_64
    MicroInstruction(op=MicroOp.LDC, w=IW.W64, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=14),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_LOG2_10_32
    MicroInstruction(op=MicroOp.LDC, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=16),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_LOG2_10_64
    MicroInstruction(op=MicroOp.LDC, w=IW.W64, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=18),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_LOG10_2_32
    MicroInstruction(op=MicroOp.LDC, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=20),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_LOG10_2_64
    MicroInstruction(op=MicroOp.LDC, w=IW.W64, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=22),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_SQRT2_32
    MicroInstruction(op=MicroOp.LDC, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=24),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_SQRT2_64
    MicroInstruction(op=MicroOp.LDC, w=IW.W64, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=26),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_INV_SQRT2_32
    MicroInstruction(op=MicroOp.LDC, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=28),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_PUSH_INV_SQRT2_64
    MicroInstruction(op=MicroOp.LDC, w=IW.W64, dst=Reg.FL, src1=Reg.IMM, src=FpuTable.CONST, imm=30),
    MicroInstruction(op=MicroOp.PUSH, w=IW.W64, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM0_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=653),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM1_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=657),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=1),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM2_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=661),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=2),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM3_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=665),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=3),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM4_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=669),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=4),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM5_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=673),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=5),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM6_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=677),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=6),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM7_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=681),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=7),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM8_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=685),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=8),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM9_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=689),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=9),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM10_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=693),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=10),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM11_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=697),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=11),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM12_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=701),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=12),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM13_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=705),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=13),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM14_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=709),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=14),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_MEM15_TOS
    MicroInstruction(op=MicroOp.POP, dst=Reg.FL),
    MicroInstruction(op=MicroOp.JNZ, flag=StatusFlag.UNDERFLOW, imm=713),
    MicroInstruction(op=MicroOp.STO, src=Reg.FL, imm=15),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM0
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM1
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=1),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM2
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=2),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM3
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=3),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM4
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=4),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM5
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=5),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM6
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=6),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM7
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=7),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM8
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=8),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM9
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=9),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM10
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=10),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM11
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=11),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM12
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=12),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM13
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=13),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM14
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=14),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_CP_TOS_MEM15
    MicroInstruction(op=MicroOp.LD, dst=Reg.FL, imm=15),
    MicroInstruction(op=MicroOp.PUSH, src=Reg.FL),
    MicroInstruction(op=MicroOp.HALT),

    # USER_ZERO_MEM
    MicroInstruction(op=MicroOp.XOR, dst=Reg.AL, src=Reg.AL),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=1),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=2),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=3),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=4),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=5),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=6),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=7),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=8),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=9),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=10),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=11),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=12),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=13),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=14),
    MicroInstruction(op=MicroOp.STO, src=Reg.AL, imm=15),
    MicroInstruction(op=MicroOp.HALT),
]

# Only needs to include the instruction line of the "User_" symbols, sort them when writing to the file.
fpu_symbols: Dict[str, int] = {
    "USER_ABS_F32": 564,
    "USER_ABS_F64": 569,
    "USER_ABS_I32": 574,
    "USER_ABS_I64": 583,
    "USER_ADD_F32": 0,
    "USER_ADD_I32": 49,
    "USER_ADD_I64": 56,
    "USER_CHS_F32": 542,
    "USER_CHS_F64": 547,
    "USER_CHS_I32": 552,
    "USER_CHS_I64": 558,
    "USER_CP_MEM0_TOS": 650,
    "USER_CP_MEM10_TOS": 690,
    "USER_CP_MEM11_TOS": 694,
    "USER_CP_MEM12_TOS": 698,
    "USER_CP_MEM13_TOS": 702,
    "USER_CP_MEM14_TOS": 706,
    "USER_CP_MEM15_TOS": 710,
    "USER_CP_MEM1_TOS": 654,
    "USER_CP_MEM2_TOS": 658,
    "USER_CP_MEM3_TOS": 662,
    "USER_CP_MEM4_TOS": 666,
    "USER_CP_MEM5_TOS": 670,
    "USER_CP_MEM6_TOS": 674,
    "USER_CP_MEM7_TOS": 678,
    "USER_CP_MEM8_TOS": 682,
    "USER_CP_MEM9_TOS": 686,
    "USER_CP_TOS_MEM0": 714,
    "USER_CP_TOS_MEM1": 717,
    "USER_CP_TOS_MEM10": 744,
    "USER_CP_TOS_MEM11": 747,
    "USER_CP_TOS_MEM12": 750,
    "USER_CP_TOS_MEM13": 753,
    "USER_CP_TOS_MEM14": 756,
    "USER_CP_TOS_MEM15": 759,
    "USER_CP_TOS_MEM2": 720,
    "USER_CP_TOS_MEM3": 723,
    "USER_CP_TOS_MEM4": 726,
    "USER_CP_TOS_MEM5": 729,
    "USER_CP_TOS_MEM6": 732,
    "USER_CP_TOS_MEM7": 735,
    "USER_CP_TOS_MEM8": 738,
    "USER_CP_TOS_MEM9": 741,
    "USER_DIV_F32": 183,
    "USER_DIV_I32": 225,
    "USER_DUP4": 592,
    "USER_DUP8": 597,
    "USER_EXP2_F32": 425,
    "USER_LOG2_F32": 292,
    "USER_MUL_F32": 127,
    "USER_MUL_I32": 154,
    "USER_MUL_I64": 161,
    "USER_PUSH_E_32": 608,
    "USER_PUSH_E_64": 611,
    "USER_PUSH_INV_SQRT2_32": 644,
    "USER_PUSH_INV_SQRT2_64": 647,
    "USER_PUSH_LN2_32": 614,
    "USER_PUSH_LN2_64": 617,
    "USER_PUSH_LOG10_2_32": 632,
    "USER_PUSH_LOG10_2_64": 635,
    "USER_PUSH_LOG2E_32": 620,
    "USER_PUSH_LOG2E_64": 623,
    "USER_PUSH_LOG2_10_32": 626,
    "USER_PUSH_LOG2_10_64": 629,
    "USER_PUSH_PI_32": 602,
    "USER_PUSH_PI_64": 605,
    "USER_PUSH_SQRT2_32": 638,
    "USER_PUSH_SQRT2_64": 641,
    "USER_SQRT_F32": 233,
    "USER_SUB_F32": 63,
    "USER_SUB_I32": 113,
    "USER_SUB_I64": 120,
    "USER_ZERO_MEM": 762,
}
