`timescale 1ns/1ps

module zx50_mmu_sram_tb;

    // --- 1. System Clocks (Generated by Timebase) ---
    wire mclk, zclk;
    zx50_clock clk_gen (
        .mclk(mclk),
        .zclk(zclk)
    );

    // --- 2. System Signals ---
    reg reset_n;
    reg [3:0] id_sw;

    // --- 3. Z80 Backplane Buses (Driven by BFM) ---
    wire [15:0] z80_addr;
    wire [7:0]  z80_data;
    wire z80_mreq_n, z80_iorq_n, z80_rd_n, z80_wr_n, z80_m1_n;
    
    // --- 4. MMU / ATL Wires ---
    wire [3:0] atl_addr;
    wire [7:0] atl_data; 
    wire atl_we_n, atl_oe_n, atl_ce_n;
    wire active, z80_card_hit, is_busy;
    wire mmu_is_initializing;
    wire mmu_cpu_updating;
    wire [7:0] mmu_l_data;
    wire [3:0] mmu_init_ptr;

    // --- 5. BFM Instantiations ---

    // BRIDGE LOGIC: Connect the Z80 BFM bus to the MMU snoop port
    assign mmu_l_data = z80_data;

    // VERIFICATION LOOPBACK: Bridge translation results to Z80 bus for BFM check
    // This allows z80.mem_read to "see" the physical page output from the LUT 
    assign z80_data = (active && !z80_rd_n) ? atl_data : 8'hzz;

    // The Z80 Bus Master (Corrected to z80_cpu_util)
    z80_cpu_util z80 (
        .clk(zclk), .addr(z80_addr), .data(z80_data),
        .mreq_n(z80_mreq_n), .iorq_n(z80_iorq_n), 
        .rd_n(z80_rd_n), .wr_n(z80_wr_n), .m1_n(z80_m1_n),
        .wait_n(1'b1) // No wait states needed for isolated MMU testing
    );

    // The Device Under Test
    zx50_mmu_sram dut (
        .mclk(mclk), .reset_n(reset_n), .card_id_sw(id_sw),
        .z80_addr(z80_addr), .l_addr_hi(z80_addr[15:12]), .l_data(z80_data),
        .z80_iorq_n(z80_iorq_n), .z80_wr_n(z80_wr_n), .z80_mreq_n(z80_mreq_n),
        .atl_addr(atl_addr), .atl_we_n(atl_we_n), .atl_oe_n(atl_oe_n),
        .active(active), .z80_card_hit(z80_card_hit), .is_busy(is_busy),
        .cpu_updating(mmu_cpu_updating),
        .is_initializing(mmu_is_initializing), 
        .init_ptr(mmu_init_ptr)
    );

    // The Structural LUT SRAM 
    // Note: Since this is just the isolated MMU, we mock the top-level CE logic here
    assign atl_ce_n = !(z80_card_hit || is_busy);
    assign atl_data = mmu_is_initializing ? {4'h0, mmu_init_ptr} : 
                      (mmu_cpu_updating   ? z80_data : 8'hzz);

    is61c256al lut_sram (
        .addr({11'b0, atl_addr}), // Pad the 4-bit ATL address to fit the 15-bit chip
        .data(atl_data),
        .ce_n(atl_ce_n), .oe_n(atl_oe_n), .we_n(atl_we_n)
    );

    // --- 6. Test Sequence ---
    reg [7:0] dummy_data;
    reg phase1_active_ok;

    initial begin
        $dumpfile("waves/zx50_mmu_sram.vcd");
        $dumpvars(0, zx50_mmu_sram_tb);

        // Setup: Card ID is 0.
        id_sw = 4'h0;

        // Boot Sequence 
        reset_n = 1;      
        clk_gen.wait_mclk(5); 
        reset_n = 0;  
        clk_gen.wait_mclk(50);
        reset_n = 1; 

        // The simulated Z80 Boot ROM initializes the MMU maps
        z80.init_mmu(4'h0); // Init Card A

        // Concurrently read memory and check if the MMU flags 'active'
        fork
            z80.mem_read(16'h0000, dummy_data);
            begin
                @(negedge z80_rd_n);
                phase1_active_ok = active;
            end
        join

        // The 'join' ensures the Z80 read cycle is fully complete.
        // Now we can safely check the data returned by the BFM.
        
        if (phase1_active_ok && dummy_data === 8'h00) begin 
            $display("****** PHASE 1 PASSED: Memory claimed, translated to Page 0 ******");
        end else begin
            $display("!!!!!! PHASE 1 FAILED: active_ok=%b, dummy_data=%h !!!!!!", phase1_active_ok, dummy_data);
            $fatal(1);
        end

        z80.wait_cycles(5);

        // ==========================================
        // PHASE 2: Dynamic MMU Reprogramming Check
        // ==========================================
        $display("[%0t] --- Testing Phase 2: Z80 MMU I/O Write ---", $time); 
        
        z80.io_write(16'h0030, 8'hAA); 
        z80.wait_cycles(5);

        // ==========================================
        // PHASE 3: Translation Verification
        // ==========================================
        $display("[%0t] --- Testing Phase 3: Translation Verification ---", $time); 
        
        z80.mem_read(16'h0000, dummy_data);

        if (dummy_data === 8'hAA) begin
            $display("****** PHASE 3 PASSED: SRAM successfully updated to 0xAA ******");
        end else begin
            $display("!!!!!! PHASE 3 FAILED: dummy_data=%h (Expected 0xAA) !!!!!!", dummy_data);
            $fatal(1);
        end

        z80.wait_cycles(5); 

        $display("====================================================="); 
        $display(" SUCCESS: All MMU Tests Passed.");
        $display("=====================================================");
        $finish;
    end

    // --- System Watchdog Timer ---
    initial begin
        #150000;
        $display("FATAL [%0t]: Watchdog Timer Expired! Testbench deadlock detected.", $time); 
        $fatal(1);
    end

endmodule