`timescale 1ns/1ps

/***************************************************************************************
 * MODULE: zx50_mem_card_nodma_tb
 * DESCRIPTION:
 * [REVISION: "No-DMA" Fallback Variant. Tests the complete physical digital twin 
 * of the card (CPLD + Transceivers + SRAMs) with the Shadow DMA Backplane completely 
 * omitted from the test harness.]
 * * The top-level integration test. This proves that the CPLD core correctly manages 
 * the external SRAM models and physically routes the bidirectional data across the 
 * 74ABT245 transceivers from the Z80 BFM all the way into the memory array and back.
 ***************************************************************************************/

module zx50_mem_card_nodma_tb;

    // --- 1. System Clocks (Generated by Timebase) ---
    wire mclk, zclk;
    zx50_clock clk_gen (
        .mclk(mclk),
        .zclk(zclk)
    );

    // --- 2. System Signals ---
    reg reset_n;
    reg [3:0] card_id;
    reg z80_iei;

    // --- 3. Z80 Backplane Buses (Driven by BFM) ---
    wire [15:0] z80_addr;
    wire [7:0]  z80_data;
    wire z80_mreq_n, z80_iorq_n, z80_wr_n, z80_rd_n, z80_m1_n;
    wire z80_wait_n, z80_ieo, z80_int_n;

    // [REVISION: 4. Shadow Bus (Mock - Inactive) section completely removed. 
    // The NoDMA card no longer accepts or drives these backplane pins.]

    // --- 5. BFM Instantiations ---

    // The Z80 Bus Master
    z80_cpu_util z80 (
        .clk(zclk),
        .addr(z80_addr),
        .data(z80_data),
        .mreq_n(z80_mreq_n),
        .iorq_n(z80_iorq_n),
        .rd_n(z80_rd_n),
        .wr_n(z80_wr_n),
        .m1_n(z80_m1_n),
        .wait_n(z80_wait_n)
    );

    // [REVISION: The Device Under Test is now the NoDMA Digital Twin]
    zx50_mem_card_nodma dut (
        .mclk(mclk), .reset_n(reset_n), .card_id_sw(card_id),
        .z80_addr(z80_addr), .z80_data(z80_data),
        .z80_mreq_n(z80_mreq_n), .z80_iorq_n(z80_iorq_n), .z80_wr_n(z80_wr_n), .z80_rd_n(z80_rd_n),
        .z80_m1_n(z80_m1_n), .z80_iei(z80_iei),
        .z80_wait_n(z80_wait_n), .z80_ieo(z80_ieo), .z80_int_n(z80_int_n)
        
        // [REVISION: Shadow bus mappings removed from instantiation]
    );

    // --- 6. Test Sequence ---
    reg [7:0] read_val;

    initial begin
        // [REVISION: Updated dumpfile name to isolate NoDMA wave results]
        $dumpfile("waves/zx50_mem_card_nodma.vcd");
        $dumpvars(0, zx50_mem_card_nodma_tb);

        // Initial setup
        card_id = 4'h0; z80_iei = 1;

        // Boot Sequence
        reset_n = 1;      
        clk_gen.wait_mclk(5); // Wait a few clock cycles
        reset_n = 0;  
        clk_gen.wait_mclk(50); // Hold reset active for a while
        reset_n = 1;

        // Wait for the 16-cycle MMU Hardware Wipe to finish
        clk_gen.wait_mclk(20);

        // ==========================================
        // STEP 1: Program MMU
        // ==========================================
        // We write to the MMU's internal registers to map a Z80 Logical Page 
        // to a physical location in the SRAM chips.
        $display("[%0t] Step 1: Programming MMU Page 0...", $time);
        
        // I/O Port 0x30 = Target Bank 0x0 on Card 0
        // Data 0x85 = The Physical Page to route Bank 0x0 to.
        z80.io_write(16'h0030, 8'h85); 

        // Wait a few Z80 T-States before the next command
        z80.wait_cycles(5);

        // ==========================================
        // STEP 2: Write to SRAM
        // ==========================================
        // The Z80 writes payload data to the logical page we just mapped.
        // The CPLD must detect the hit, translate the address via the LUT, 
        // enable the transceivers, and pulse the correct physical SRAM chip.
        $display("[%0t] Step 2: Writing to SRAM...", $time);
        
        // Target Logical Bank 0x0, Offset 0x0123. (Will map to physical 0x85123)
        z80.mem_write(16'h0123, 8'hA5);

        z80.wait_cycles(5);

        // ==========================================
        // STEP 3: Read back from SRAM
        // ==========================================
        // The Z80 reads back the payload data to verify the write path, the 
        // storage medium, and the read path all worked flawlessly.
        $display("[%0t] Step 3: Reading back from SRAM...", $time);
        
        z80.mem_read(16'h0123, read_val);

        // Validation Check
        if (read_val === 8'hA5) begin
            $display("=====================================================");
            $display(" SUCCESS: Full System Integration Test Passed (NoDMA)!");
            $display(" Data Match: MMU, SRAM, and Transceivers working perfectly.");
            $display("=====================================================");
        end 
        else begin
            $display("!!! FAILURE: Expected A5, got %h !!!", read_val);
            $fatal(1);
        end

        z80.wait_cycles(5);
        $finish;
    end

    // --- System Watchdog Timer ---
    initial begin
        #150000;
        $display("FATAL [%0t]: Watchdog Timer Expired! Testbench deadlock detected.", $time);
        $fatal(1);
    end

endmodule