`timescale 1ns/1ps

/***************************************************************************************
 * MODULE: zx50_fpu_mem
 * FILE: src/zx50_fpu_mem.v
 * DESCRIPTION:
 * Private Memory Controller & Bus Arbiter for Zx50 FPU Coprocessor (CPLD Rev C2).
 *
 * TIMING ARCHITECTURE:
 * 1. Private SRAM (IS61C256AL-12TLI, 12ns access time):
 *    - READ : Single-cycle combinational ready (12ns < 25ns/50ns clock period).
 *    - WRITE: 2-phase write strobe generator with address latching across write edge.
 * 2. Private Flash ROM (SST39SF040, 55ns access time):
 *    - READ : Dynamic multi-cycle counter (3 cycles @ 40MHz, 2 cycles @ 20MHz).
 *    - Handshake: Asserts mem_ready pulse when access window clears t_ACC requirement.
 ***************************************************************************************/

module zx50_fpu_mem (
    input  wire        mclk,            // Coprocessor High-Speed Clock (20MHz / 40MHz)
    input  wire        reset_n,         // Global System Reset (Active LOW)
    input  wire        clk_spd,         // Speed Select (1 = 40MHz Fast, 0 = 20MHz Slow)

    // --- Client 0: Host Port 0x70 Interface (Z80 PUSH / POP - SRAM Only) ---
    input  wire        host_we_req,     // Host PUSH write request pulse/level
    input  wire        host_oe_req,     // Host POP read output enable request
    input  wire [7:0]  host_addr,       // Target address from host interface (SP or SP-1)
    input  wire [7:0]  host_wdata,      // Data payload written by host CPU

    // --- Client 1: Coprocessor Engine Interface (ALU / Management / Flash LUT) ---
    input  wire        eng_we_req,      // Coprocessor SRAM write request
    input  wire        eng_oe_req,      // Coprocessor read output enable request
    input  wire        eng_sel_flash,   // 1 = Target Flash ROM (U13), 0 = Target SRAM (U12)
    input  wire [14:0] eng_addr,        // 15-bit target address generated by math engine
    input  wire [7:0]  eng_wdata,       // Data payload written by math engine

    // --- Readback Data & Handshake ---
    output wire [7:0]  mem_rdata,       // Continuous read data captured off private cd bus
    output wire        mem_ready,       // 1 = Read valid or Write complete

    // --- Physical IS61C256AL (U12) & SST39SF040 (U13) Pin Drivers ---
    output wire [14:0] ca,              // 15-bit Private Address Bus (32KB active region)
    inout  wire [7:0]  cd,              // 8-bit Private Bidirectional Data Bus
    output wire        m_ce_n,          // Private SRAM ~CE (Chip Enable)
    output wire        c_oe_n,          // Common private ~OE (SRAM/Flash Output Enable)
    output wire        c_we_n,          // Common private ~WE (SRAM/Flash Write Enable)
    output wire        f_ce_n           // Private Flash ~CE (Chip Enable)
);

    // =========================================================================
    // 1. Request Arbitration & Signal Multiplexing
    // =========================================================================
    wire eng_active = eng_we_req || eng_oe_req;

    // Route 15-bit address: Engine provides full 15 bits; Host provides 8-bit SP
    wire [14:0] active_addr = eng_active ? eng_addr : {7'b0000000, host_addr};
    
    // SRAM vs Flash request target decoding
    wire is_flash_access = eng_active && eng_sel_flash;
    wire is_sram_access  = !is_flash_access;

    // Disambiguate read/write strobes based on active target memory chip
    wire active_sram_we_req  = is_sram_access  && (eng_we_req || host_we_req);
    wire active_sram_oe_req  = is_sram_access  && (eng_oe_req || host_oe_req);
    wire active_flash_oe_req = is_flash_access && eng_oe_req;

    // Data payload multiplexer
    wire [7:0] active_wdata = eng_we_req ? eng_wdata : host_wdata;

    // Target Flash cycle count: 3 cycles at 40MHz (clk_spd=1), 2 cycles at 20MHz (clk_spd=0)
    wire [1:0] flash_target = clk_spd ? 2'd3 : 2'd2;

    // =========================================================================
    // 2. SRAM Write Pipeline & Flash Read Counter
    // =========================================================================
    reg        sram_we_strobe;
    reg        sram_we_hold;
    reg [14:0] latched_write_addr;
    reg [1:0]  flash_cnt;

    always @(posedge mclk or negedge reset_n) begin
        if (!reset_n) begin
            sram_we_strobe     <= 1'b0;
            sram_we_hold       <= 1'b0;
            latched_write_addr <= 15'h0000;
            flash_cnt          <= 2'd0;
        end else begin
            // --- SRAM Write Pipeline ---
            if (active_sram_we_req && !sram_we_strobe && !sram_we_hold) begin
                sram_we_strobe     <= 1'b1;
                sram_we_hold       <= 1'b0;
                latched_write_addr <= active_addr;
            end else if (sram_we_strobe) begin
                sram_we_strobe     <= 1'b0;
                sram_we_hold       <= 1'b1;
            end else begin
                sram_we_strobe     <= 1'b0;
                sram_we_hold       <= 1'b0;
            end

            // --- Flash Read Cycle Counter ---
            if (active_flash_oe_req) begin
                if (flash_cnt < flash_target) begin
                    flash_cnt <= flash_cnt + 1'b1;
                end
            end else begin
                flash_cnt <= 2'd0;
            end
        end
    end

    // =========================================================================
    // 3. Ready Handshake Decoding
    // =========================================================================
    wire sram_rd_ready  = active_sram_oe_req;
    wire sram_wr_ready  = sram_we_hold;
    wire flash_rd_ready = active_flash_oe_req && (flash_cnt == flash_target);

    assign mem_ready = sram_rd_ready || sram_wr_ready || flash_rd_ready;

    // =========================================================================
    // 4. Physical Pin Assignments & Tri-State Control Logic
    // =========================================================================
    wire sram_write_active = (sram_we_strobe || sram_we_hold);

    // Drive 15-bit Private Address Bus
    assign ca = sram_write_active ? latched_write_addr : active_addr;

    // Private Chip Enable Controls (Active LOW)
    assign m_ce_n = !(sram_write_active || active_sram_oe_req);
    assign f_ce_n = !active_flash_oe_req;

    // Consolidated Shared Control Strobes (Active LOW)
    assign c_oe_n = !(active_sram_oe_req || active_flash_oe_req);
    assign c_we_n = !sram_we_strobe;

    // Private Data Bus Routing
    assign cd        = sram_write_active ? active_wdata : 8'hzz;
    assign mem_rdata = cd;

endmodule