`timescale 1ns/1ps

/***************************************************************************************
 * MODULE: zx50_fpu_mem
 * FILE: src/zx50_fpu_mem.v
 * DESCRIPTION:
 * Private Memory Controller & Bus Arbiter for the Zx50 FPU Coprocessor (CPLD Rev C1).
 *
 * ARCHITECTURAL SPECIFICATION:
 * - Decouples private memory traffic from the main Z80 backplane bus.
 * - Controls both Private SRAM (IS61C5128AS - U12, 25ns) and Private Flash ROM
 *   (SST39SF040 - U13, 55ns) over a shared 14-bit address bus (CA[13:0]) and 8-bit
 *   bidirectional data bus (CD[7:0]).
 *
 * DUAL-CLIENT ARBITRATION:
 *   - Client 0 (Host Port 0x70): PUSH / POP operations initiated by the Z80 host.
 *     Targets first 256 bytes of SRAM (CA[13:8] = 0x00, CA[7:0] = SP).
 *   - Client 1 (Coprocessor Engine): Internal math operations (ALU fetch/store, DUP_TOS)
 *     and Flash ROM lookup table (LUT) fetches (SIN, COS, LOG, EXP seed tables).
 *   - Priority: The Coprocessor Engine (Client 1) takes priority when active; otherwise,
 *     the Host Z80 interface (Client 0) retains default control of the private bus.
 *
 * 2-PHASE WRITE PIPELINE (SRAM):
 *   - Phase 1 (Strobe): m_we_n = 0, cd = wdata, ca = addr (1 MCLK tick)
 *   - Phase 2 (Hold)  : m_we_n = 1, cd = wdata, ca = addr (1 MCLK tick - data latched on posedge m_we_n)
 *   - Phase 3 (Idle)  : m_we_n = 1, cd = High-Z
 *   * Note: Holding cd driven during Phase 2 satisfies the Data Hold Time (t_DH)
 *     requirement of the IS61C5128AS SRAM silicon.
 ***************************************************************************************/

module zx50_fpu_mem (
    input  wire        mclk,            // Coprocessor High-Speed Clock (20MHz / 40MHz)
    input  wire        reset_n,         // Global System Reset (Active LOW)

    // --- Client 0: Host Port 0x70 Interface (Z80 PUSH / POP - SRAM Only) ---
    input  wire        host_we_req,     // Host PUSH write request pulse/level
    input  wire        host_oe_req,     // Host POP read output enable request
    input  wire [7:0]  host_addr,       // Target address from host interface (SP or SP-1)
    input  wire [7:0]  host_wdata,      // Data payload written by host CPU

    // --- Client 1: Coprocessor Engine Interface (ALU / Management / Flash LUT) ---
    input  wire        eng_we_req,      // Coprocessor SRAM write request
    input  wire        eng_oe_req,      // Coprocessor read output enable request
    input  wire        eng_sel_flash,   // 1 = Target Flash ROM (U13), 0 = Target SRAM (U12)
    input  wire [13:0] eng_addr,        // 14-bit target address generated by math engine
    input  wire [7:0]  eng_wdata,       // Data payload written by math engine

    // --- Shared Readback Data Bus ---
    output wire [7:0]  mem_rdata,       // Continuous read data captured off private cd bus

    // --- Physical IS61C5128AS (U12) SRAM Pin Drivers ---
    output wire [13:0] ca,              // 14-bit Private Address Bus (16KB active region)
    inout  wire [7:0]  cd,              // 8-bit Private Bidirectional Data Bus
    output wire        m_ce_n,          // Private SRAM Chip Enable (~CE)
    output wire        m_oe_n,          // Private SRAM Output Enable (~OE)
    output wire        m_we_n,          // Private SRAM Write Enable (~WE)

    // --- Physical SST39SF040 (U13) Flash ROM Pin Drivers ---
    output wire        f_ce_n,          // Private Flash Chip Enable (~CE)
    output wire        f_oe_n,          // Private Flash Output Enable (~OE)
    output wire        f_we_n           // Private Flash Write Enable (~WE)
);

    // =========================================================================
    // 1. Request Arbitration & Signal Multiplexing
    // =========================================================================
    // Client 1 (Engine) takes ownership whenever either read or write request is active
    wire eng_active = eng_we_req || eng_oe_req;

    // Route 14-bit address: Engine provides full 14 bits; Host provides 8-bit SP (upper bits cleared)
    wire [13:0] active_addr = eng_active ? eng_addr : {6'b000000, host_addr};
    
    // SRAM vs Flash request target decoding
    wire is_flash_access = eng_active && eng_sel_flash;
    wire is_sram_access  = !is_flash_access;

    // Disambiguate read/write strobes based on active target memory chip
    wire active_sram_we_req  = is_sram_access  && (eng_we_req || host_we_req);
    wire active_sram_oe_req  = is_sram_access  && (eng_oe_req || host_oe_req);
    wire active_flash_oe_req = is_flash_access && eng_oe_req;

    // Data payload multiplexer
    wire [7:0] active_wdata = eng_we_req ? eng_wdata : host_wdata;

    // =========================================================================
    // 2. 2-Phase SRAM Write Timing Controller (MCLK Domain)
    // =========================================================================
    // Guarantees proper data hold time (t_DH) on posedge m_we_n:
    //   Phase 1 (Strobe): m_we_n = 0, cd = wdata, ca = addr
    //   Phase 2 (Hold)  : m_we_n = 1, cd = wdata, ca = addr (data latched on posedge m_we_n!)
    //   Phase 3 (Idle)  : m_we_n = 1, cd = High-Z
    reg sram_we_strobe;
    reg sram_we_hold;

    always @(posedge mclk or negedge reset_n) begin
        if (!reset_n) begin
            sram_we_strobe <= 1'b0;
            sram_we_hold   <= 1'b0;
        end else begin
            if (active_sram_we_req && !sram_we_strobe && !sram_we_hold) begin
                // Phase 1: Drive write strobe LOW
                sram_we_strobe <= 1'b1;
                sram_we_hold   <= 1'b0;
            end else if (sram_we_strobe) begin
                // Phase 2: Raise write strobe HIGH to trigger memory write edge while keeping bus driven
                sram_we_strobe <= 1'b0;
                sram_we_hold   <= 1'b1;
            end else begin
                // Phase 3: Release private data bus back to High-Z
                sram_we_strobe <= 1'b0;
                sram_we_hold   <= 1'b0;
            end
        end
    end

    // =========================================================================
    // 3. Physical Pin Assignments & Tri-State Control Logic
    // =========================================================================
    // Active write window spans Phase 1 (Strobe) and Phase 2 (Hold)
    wire sram_write_active = (sram_we_strobe || sram_we_hold);

    // Drive shared 14-bit Private Address Bus
    assign ca = active_addr;

    // Private SRAM (U12) Controls (Active LOW)
    assign m_ce_n = !(sram_write_active || active_sram_oe_req);
    assign m_we_n = !sram_we_strobe; // Active LOW ONLY during Phase 1
    assign m_oe_n = !active_sram_oe_req;

    // Private Flash ROM (U13) Controls (Read-Only during math execution)
    assign f_ce_n = !active_flash_oe_req;
    assign f_oe_n = !active_flash_oe_req;
    assign f_we_n = 1'b1; // Flash programming disabled during math execution

    // Private Data Bus Routing
    assign cd        = sram_write_active ? active_wdata : 8'hzz;
    assign mem_rdata = cd; // Sample internal read data from private bus

endmodule
