`timescale 1ns/1ps

/***************************************************************************************
 * MODULE: zx50_fpu_mem
 * FILE: src/zx50_fpu_mem.v
 * DESCRIPTION:
 * Private Memory Controller & Bus Arbiter for Zx50 FPU Coprocessor (CPLD Rev C2).
 *
 * DYNAMIC TIMING SCALING (clk_spd input):
 * 1. clk_spd = 1 (40 MHz MCLK, T_clk = 25ns):
 *    - SRAM Read : 1 Cycle (12ns < 25ns)
 *    - Flash Read: 3 Cycles (75ns > 55ns t_ACC)
 * 2. clk_spd = 0 (20 MHz MCLK, T_clk = 50ns):
 *    - SRAM Read : 1 Cycle (12ns < 50ns)
 *    - Flash Read: 2 Cycles (100ns > 55ns t_ACC)
 ***************************************************************************************/

module zx50_fpu_mem (
    input  wire        mclk,            // Coprocessor High-Speed Clock (20MHz / 40MHz)
    input  wire        reset_n,         // Global System Reset (Active LOW)
    input  wire        clk_spd,         // Speed Select (1 = 40MHz Fast, 0 = 20MHz Slow)

    // --- Client 0: Host Port 0x70 Interface (Z80 PUSH / POP - SRAM Only) ---
    input  wire        host_we_req,     // Host PUSH write request pulse/level
    input  wire        host_oe_req,     // Host POP read output enable request
    input  wire [7:0]  host_addr,       // Target address from host interface (SP or SP-1)
    input  wire [7:0]  host_wdata,      // Data payload written by host CPU

    // --- Client 1: Coprocessor Engine Interface (ALU / Management / Flash LUT) ---
    input  wire        eng_we_req,      // Coprocessor SRAM write request
    input  wire        eng_oe_req,      // Coprocessor read output enable request
    input  wire        eng_sel_flash,   // 1 = Target Flash ROM (U13), 0 = Target SRAM (U12)
    input  wire [14:0] eng_addr,        // 15-bit target address generated by math engine
    input  wire [7:0]  eng_wdata,       // Data payload written by math engine

    // --- Readback Data & Handshake ---
    output wire [7:0]  mem_rdata,       // Continuous read data captured off private cd bus
    output reg         mem_ready,       // 1 = Data valid (Read) or Write Complete (Write)

    // --- Physical IS61C256AL (U12) & SST39SF040 (U13) Pin Drivers ---
    output wire [14:0] ca,              // 15-bit Private Address Bus (32KB active region)
    inout  wire [7:0]  cd,              // 8-bit Private Bidirectional Data Bus
    output wire        m_ce_n,          // Private SRAM ~CE (Chip Enable)
    output wire        c_oe_n,          // Common private ~OE (SRAM/Flash Output Enable)
    output wire        c_we_n,          // Common private ~WE (SRAM/Flash Write Enable)
    output wire        f_ce_n           // Private Flash ~CE (Chip Enable)
);

    // =========================================================================
    // 1. Request Arbitration & Signal Multiplexing
    // =========================================================================
    wire eng_active = eng_we_req || eng_oe_req;

    // Route 15-bit address: Engine provides full 15 bits; Host provides 8-bit SP (upper bits cleared)
    wire [14:0] active_addr = eng_active ? eng_addr : {7'b0000000, host_addr};
    
    // SRAM vs Flash request target decoding
    wire is_flash_access = eng_active && eng_sel_flash;
    wire is_sram_access  = !is_flash_access;

    // Disambiguate read/write strobes based on active target memory chip
    wire active_sram_we_req  = is_sram_access  && (eng_we_req || host_we_req);
    wire active_sram_oe_req  = is_sram_access  && (eng_oe_req || host_oe_req);
    wire active_flash_oe_req = is_flash_access && eng_oe_req;

    // Data payload multiplexer
    wire [7:0] active_wdata = eng_we_req ? eng_wdata : host_wdata;

    // =========================================================================
    // 2. 2-Phase SRAM Write Controller (12ns Fast SRAM)
    // =========================================================================
    reg sram_we_strobe;
    reg sram_we_hold;

    always @(posedge mclk or negedge reset_n) begin
        if (!reset_n) begin
            sram_we_strobe <= 1'b0;
            sram_we_hold   <= 1'b0;
        end else begin
            if (active_sram_we_req && !sram_we_strobe && !sram_we_hold) begin
                sram_we_strobe <= 1'b1;
                sram_we_hold   <= 1'b0;
            end else if (sram_we_strobe) begin
                sram_we_strobe <= 1'b0;
                sram_we_hold   <= 1'b1;
            end else begin
                sram_we_strobe <= 1'b0;
                sram_we_hold   <= 1'b0;
            end
        end
    end

    // =========================================================================
    // 3. Dynamic Flash Read Controller (55ns Slow Flash ROM)
    // =========================================================================
    // Target threshold:
    //   clk_spd = 1 (40 MHz): Target is Cycle 3 (flash_cycle_cnt == 2'd2) -> 75ns > 55ns
    //   clk_spd = 0 (20 MHz): Target is Cycle 2 (flash_cycle_cnt == 2'd1) -> 100ns > 55ns
    wire [1:0] flash_target_cycles = clk_spd ? 2'd2 : 2'd1;
    reg  [1:0] flash_cycle_cnt;

    always @(posedge mclk or negedge reset_n) begin
        if (!reset_n) begin
            flash_cycle_cnt <= 2'd0;
            mem_ready       <= 1'b0;
        end else begin
            if (active_flash_oe_req) begin
                if (flash_cycle_cnt < flash_target_cycles) begin
                    flash_cycle_cnt <= flash_cycle_cnt + 1'b1;
                    mem_ready       <= 1'b0; // Wait state
                end else begin
                    mem_ready       <= 1'b1; // Access complete!
                end
            end else if (active_sram_we_req) begin
                // SRAM Write: Ready on Phase 2 hold completion
                mem_ready <= sram_we_hold;
            end else if (active_sram_oe_req) begin
                // SRAM Read: Single cycle ready
                mem_ready <= 1'b1;
            end else begin
                flash_cycle_cnt <= 2'd0;
                mem_ready       <= 1'b0;
            end
        end
    end

    // =========================================================================
    // 4. Physical Pin Assignments & Tri-State Control Logic
    // =========================================================================
    wire sram_write_active = (sram_we_strobe || sram_we_hold);

    // Drive shared 15-bit Private Address Bus
    assign ca = active_addr;

    // Private Chip Enable Controls (Active LOW)
    assign m_ce_n = !(sram_write_active || active_sram_oe_req);
    assign f_ce_n = !active_flash_oe_req;

    // Consolidated Shared Control Strobes (Active LOW)
    assign c_oe_n = !(active_sram_oe_req || active_flash_oe_req);
    assign c_we_n = !sram_we_strobe; // Active LOW write pulse during Phase 1

    // Private Data Bus Routing
    assign cd        = sram_write_active ? active_wdata : 8'hzz;
    assign mem_rdata = cd; // Sample internal read data from private bus

endmodule